// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/mumbleway.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiMumblewayInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1635120130;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_mumbleway',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiMumblewayAcceptCertificate({required String serverId});

  Future<String> crateApiMumblewayAddServer({required ServerConfig config});

  Stream<AppEvent> crateApiMumblewayAppEvents();

  Future<List<String>> crateApiMumblewayAudioInputDevices();

  Future<List<String>> crateApiMumblewayAudioOutputDevices();

  Future<String> crateApiMumblewayClientCertificateFingerprint();

  Future<void> crateApiMumblewayConnectServer({required String serverId});

  int crateApiMumblewayDefaultPort();

  Future<void> crateApiMumblewayDisconnectServer({required String serverId});

  Future<void> crateApiMumblewayInitApp();

  double crateApiMumblewayInputLevelDb();

  Future<void> crateApiMumblewayJoinChannel({
    required String serverId,
    required int channelId,
  });

  int crateApiMumblewayMaxConcurrentServers();

  Future<void> crateApiMumblewayRemoveServer({required String serverId});

  Future<void> crateApiMumblewaySendText({
    required String serverId,
    required String message,
  });

  void crateApiMumblewaySetDeafened({required bool deafened});

  void crateApiMumblewaySetMicrophoneMuted({required bool muted});

  Future<void> crateApiMumblewaySetSelfMute({
    required String serverId,
    required bool muted,
  });

  void crateApiMumblewaySetTransmitting({required bool on_});

  Future<void> crateApiMumblewayStartEngine({required StartupOptions options});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiMumblewayAcceptCertificate({required String serverId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMumblewayAcceptCertificateConstMeta,
        argValues: [serverId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMumblewayAcceptCertificateConstMeta =>
      const TaskConstMeta(
        debugName: "accept_certificate",
        argNames: ["serverId"],
      );

  @override
  Future<String> crateApiMumblewayAddServer({required ServerConfig config}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_server_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMumblewayAddServerConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMumblewayAddServerConstMeta =>
      const TaskConstMeta(debugName: "add_server", argNames: ["config"]);

  @override
  Stream<AppEvent> crateApiMumblewayAppEvents() {
    final sink = RustStreamSink<AppEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_app_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiMumblewayAppEventsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMumblewayAppEventsConstMeta =>
      const TaskConstMeta(debugName: "app_events", argNames: ["sink"]);

  @override
  Future<List<String>> crateApiMumblewayAudioInputDevices() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMumblewayAudioInputDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMumblewayAudioInputDevicesConstMeta =>
      const TaskConstMeta(debugName: "audio_input_devices", argNames: []);

  @override
  Future<List<String>> crateApiMumblewayAudioOutputDevices() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMumblewayAudioOutputDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMumblewayAudioOutputDevicesConstMeta =>
      const TaskConstMeta(debugName: "audio_output_devices", argNames: []);

  @override
  Future<String> crateApiMumblewayClientCertificateFingerprint() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMumblewayClientCertificateFingerprintConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMumblewayClientCertificateFingerprintConstMeta =>
      const TaskConstMeta(
        debugName: "client_certificate_fingerprint",
        argNames: [],
      );

  @override
  Future<void> crateApiMumblewayConnectServer({required String serverId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMumblewayConnectServerConstMeta,
        argValues: [serverId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMumblewayConnectServerConstMeta =>
      const TaskConstMeta(debugName: "connect_server", argNames: ["serverId"]);

  @override
  int crateApiMumblewayDefaultPort() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_16,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMumblewayDefaultPortConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMumblewayDefaultPortConstMeta =>
      const TaskConstMeta(debugName: "default_port", argNames: []);

  @override
  Future<void> crateApiMumblewayDisconnectServer({required String serverId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMumblewayDisconnectServerConstMeta,
        argValues: [serverId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMumblewayDisconnectServerConstMeta =>
      const TaskConstMeta(
        debugName: "disconnect_server",
        argNames: ["serverId"],
      );

  @override
  Future<void> crateApiMumblewayInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMumblewayInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMumblewayInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  double crateApiMumblewayInputLevelDb() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMumblewayInputLevelDbConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMumblewayInputLevelDbConstMeta =>
      const TaskConstMeta(debugName: "input_level_db", argNames: []);

  @override
  Future<void> crateApiMumblewayJoinChannel({
    required String serverId,
    required int channelId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          sse_encode_u_32(channelId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMumblewayJoinChannelConstMeta,
        argValues: [serverId, channelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMumblewayJoinChannelConstMeta =>
      const TaskConstMeta(
        debugName: "join_channel",
        argNames: ["serverId", "channelId"],
      );

  @override
  int crateApiMumblewayMaxConcurrentServers() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMumblewayMaxConcurrentServersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMumblewayMaxConcurrentServersConstMeta =>
      const TaskConstMeta(debugName: "max_concurrent_servers", argNames: []);

  @override
  Future<void> crateApiMumblewayRemoveServer({required String serverId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMumblewayRemoveServerConstMeta,
        argValues: [serverId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMumblewayRemoveServerConstMeta =>
      const TaskConstMeta(debugName: "remove_server", argNames: ["serverId"]);

  @override
  Future<void> crateApiMumblewaySendText({
    required String serverId,
    required String message,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          sse_encode_String(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMumblewaySendTextConstMeta,
        argValues: [serverId, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMumblewaySendTextConstMeta => const TaskConstMeta(
    debugName: "send_text",
    argNames: ["serverId", "message"],
  );

  @override
  void crateApiMumblewaySetDeafened({required bool deafened}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(deafened, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMumblewaySetDeafenedConstMeta,
        argValues: [deafened],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMumblewaySetDeafenedConstMeta =>
      const TaskConstMeta(debugName: "set_deafened", argNames: ["deafened"]);

  @override
  void crateApiMumblewaySetMicrophoneMuted({required bool muted}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(muted, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMumblewaySetMicrophoneMutedConstMeta,
        argValues: [muted],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMumblewaySetMicrophoneMutedConstMeta =>
      const TaskConstMeta(
        debugName: "set_microphone_muted",
        argNames: ["muted"],
      );

  @override
  Future<void> crateApiMumblewaySetSelfMute({
    required String serverId,
    required bool muted,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(serverId, serializer);
          sse_encode_bool(muted, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMumblewaySetSelfMuteConstMeta,
        argValues: [serverId, muted],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMumblewaySetSelfMuteConstMeta =>
      const TaskConstMeta(
        debugName: "set_self_mute",
        argNames: ["serverId", "muted"],
      );

  @override
  void crateApiMumblewaySetTransmitting({required bool on_}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(on_, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMumblewaySetTransmittingConstMeta,
        argValues: [on_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMumblewaySetTransmittingConstMeta =>
      const TaskConstMeta(debugName: "set_transmitting", argNames: ["on_"]);

  @override
  Future<void> crateApiMumblewayStartEngine({required StartupOptions options}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_startup_options(options, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMumblewayStartEngineConstMeta,
        argValues: [options],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMumblewayStartEngineConstMeta =>
      const TaskConstMeta(debugName: "start_engine", argNames: ["options"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<AppEvent> dco_decode_StreamSink_app_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AppEvent dco_decode_app_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return AppEvent_Status(dco_decode_box_autoadd_status_update(raw[1]));
      case 1:
        return AppEvent_Users(
          serverId: dco_decode_String(raw[1]),
          users: dco_decode_list_ui_user(raw[2]),
        );
      case 2:
        return AppEvent_Channels(
          serverId: dco_decode_String(raw[1]),
          channels: dco_decode_list_ui_channel(raw[2]),
        );
      case 3:
        return AppEvent_Text(
          serverId: dco_decode_String(raw[1]),
          from: dco_decode_String(raw[2]),
          message: dco_decode_String(raw[3]),
        );
      case 4:
        return AppEvent_Stats(dco_decode_box_autoadd_ui_stats(raw[1]));
      case 5:
        return AppEvent_InputLevel(
          levelDb: dco_decode_f_32(raw[1]),
          speaking: dco_decode_bool(raw[2]),
        );
      case 6:
        return AppEvent_Certificate(
          serverId: dco_decode_String(raw[1]),
          fingerprint: dco_decode_String(raw[2]),
          changed: dco_decode_bool(raw[3]),
        );
      case 7:
        return AppEvent_Welcome(
          serverId: dco_decode_String(raw[1]),
          text: dco_decode_String(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ServerConfig dco_decode_box_autoadd_server_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_server_config(raw);
  }

  @protected
  StartupOptions dco_decode_box_autoadd_startup_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_startup_options(raw);
  }

  @protected
  StatusUpdate dco_decode_box_autoadd_status_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_status_update(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  UiStats dco_decode_box_autoadd_ui_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ui_stats(raw);
  }

  @protected
  ConnStatus dco_decode_conn_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ConnStatus.values[raw as int];
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<UiChannel> dco_decode_list_ui_channel(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ui_channel).toList();
  }

  @protected
  List<UiUser> dco_decode_list_ui_user(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ui_user).toList();
  }

  @protected
  MicMode dco_decode_mic_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MicMode.values[raw as int];
  }

  @protected
  NoiseSetting dco_decode_noise_setting(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NoiseSetting.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  ServerConfig dco_decode_server_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ServerConfig(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      host: dco_decode_String(arr[2]),
      port: dco_decode_u_16(arr[3]),
      username: dco_decode_String(arr[4]),
      password: dco_decode_opt_String(arr[5]),
      certFingerprint: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  StartupOptions dco_decode_startup_options(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return StartupOptions(
      storageDir: dco_decode_String(arr[0]),
      noise: dco_decode_noise_setting(arr[1]),
      micMode: dco_decode_mic_mode(arr[2]),
    );
  }

  @protected
  StatusUpdate dco_decode_status_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return StatusUpdate(
      serverId: dco_decode_String(arr[0]),
      status: dco_decode_conn_status(arr[1]),
      detail: dco_decode_String(arr[2]),
      attempt: dco_decode_u_32(arr[3]),
      retryInMs: dco_decode_u_64(arr[4]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  UiChannel dco_decode_ui_channel(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return UiChannel(
      id: dco_decode_u_32(arr[0]),
      name: dco_decode_String(arr[1]),
      parent: dco_decode_opt_box_autoadd_u_32(arr[2]),
      description: dco_decode_String(arr[3]),
    );
  }

  @protected
  UiStats dco_decode_ui_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return UiStats(
      serverId: dco_decode_String(arr[0]),
      tcpPingMs: dco_decode_f_32(arr[1]),
      udpPingMs: dco_decode_f_32(arr[2]),
      transport: dco_decode_String(arr[3]),
    );
  }

  @protected
  UiUser dco_decode_ui_user(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return UiUser(
      session: dco_decode_u_32(arr[0]),
      name: dco_decode_String(arr[1]),
      channelId: dco_decode_u_32(arr[2]),
      talking: dco_decode_bool(arr[3]),
      muted: dco_decode_bool(arr[4]),
      deafened: dco_decode_bool(arr[5]),
    );
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<AppEvent> sse_decode_StreamSink_app_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AppEvent sse_decode_app_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_status_update(deserializer);
        return AppEvent_Status(var_field0);
      case 1:
        var var_serverId = sse_decode_String(deserializer);
        var var_users = sse_decode_list_ui_user(deserializer);
        return AppEvent_Users(serverId: var_serverId, users: var_users);
      case 2:
        var var_serverId = sse_decode_String(deserializer);
        var var_channels = sse_decode_list_ui_channel(deserializer);
        return AppEvent_Channels(
          serverId: var_serverId,
          channels: var_channels,
        );
      case 3:
        var var_serverId = sse_decode_String(deserializer);
        var var_from = sse_decode_String(deserializer);
        var var_message = sse_decode_String(deserializer);
        return AppEvent_Text(
          serverId: var_serverId,
          from: var_from,
          message: var_message,
        );
      case 4:
        var var_field0 = sse_decode_box_autoadd_ui_stats(deserializer);
        return AppEvent_Stats(var_field0);
      case 5:
        var var_levelDb = sse_decode_f_32(deserializer);
        var var_speaking = sse_decode_bool(deserializer);
        return AppEvent_InputLevel(
          levelDb: var_levelDb,
          speaking: var_speaking,
        );
      case 6:
        var var_serverId = sse_decode_String(deserializer);
        var var_fingerprint = sse_decode_String(deserializer);
        var var_changed = sse_decode_bool(deserializer);
        return AppEvent_Certificate(
          serverId: var_serverId,
          fingerprint: var_fingerprint,
          changed: var_changed,
        );
      case 7:
        var var_serverId = sse_decode_String(deserializer);
        var var_text = sse_decode_String(deserializer);
        return AppEvent_Welcome(serverId: var_serverId, text: var_text);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ServerConfig sse_decode_box_autoadd_server_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_server_config(deserializer));
  }

  @protected
  StartupOptions sse_decode_box_autoadd_startup_options(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_startup_options(deserializer));
  }

  @protected
  StatusUpdate sse_decode_box_autoadd_status_update(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_status_update(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  UiStats sse_decode_box_autoadd_ui_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ui_stats(deserializer));
  }

  @protected
  ConnStatus sse_decode_conn_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ConnStatus.values[inner];
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<UiChannel> sse_decode_list_ui_channel(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <UiChannel>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ui_channel(deserializer));
    }
    return ans_;
  }

  @protected
  List<UiUser> sse_decode_list_ui_user(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <UiUser>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ui_user(deserializer));
    }
    return ans_;
  }

  @protected
  MicMode sse_decode_mic_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MicMode.values[inner];
  }

  @protected
  NoiseSetting sse_decode_noise_setting(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return NoiseSetting.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ServerConfig sse_decode_server_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_password = sse_decode_opt_String(deserializer);
    var var_certFingerprint = sse_decode_opt_String(deserializer);
    return ServerConfig(
      id: var_id,
      name: var_name,
      host: var_host,
      port: var_port,
      username: var_username,
      password: var_password,
      certFingerprint: var_certFingerprint,
    );
  }

  @protected
  StartupOptions sse_decode_startup_options(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_storageDir = sse_decode_String(deserializer);
    var var_noise = sse_decode_noise_setting(deserializer);
    var var_micMode = sse_decode_mic_mode(deserializer);
    return StartupOptions(
      storageDir: var_storageDir,
      noise: var_noise,
      micMode: var_micMode,
    );
  }

  @protected
  StatusUpdate sse_decode_status_update(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_serverId = sse_decode_String(deserializer);
    var var_status = sse_decode_conn_status(deserializer);
    var var_detail = sse_decode_String(deserializer);
    var var_attempt = sse_decode_u_32(deserializer);
    var var_retryInMs = sse_decode_u_64(deserializer);
    return StatusUpdate(
      serverId: var_serverId,
      status: var_status,
      detail: var_detail,
      attempt: var_attempt,
      retryInMs: var_retryInMs,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  UiChannel sse_decode_ui_channel(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_parent = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_description = sse_decode_String(deserializer);
    return UiChannel(
      id: var_id,
      name: var_name,
      parent: var_parent,
      description: var_description,
    );
  }

  @protected
  UiStats sse_decode_ui_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_serverId = sse_decode_String(deserializer);
    var var_tcpPingMs = sse_decode_f_32(deserializer);
    var var_udpPingMs = sse_decode_f_32(deserializer);
    var var_transport = sse_decode_String(deserializer);
    return UiStats(
      serverId: var_serverId,
      tcpPingMs: var_tcpPingMs,
      udpPingMs: var_udpPingMs,
      transport: var_transport,
    );
  }

  @protected
  UiUser sse_decode_ui_user(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_session = sse_decode_u_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_channelId = sse_decode_u_32(deserializer);
    var var_talking = sse_decode_bool(deserializer);
    var var_muted = sse_decode_bool(deserializer);
    var var_deafened = sse_decode_bool(deserializer);
    return UiUser(
      session: var_session,
      name: var_name,
      channelId: var_channelId,
      talking: var_talking,
      muted: var_muted,
      deafened: var_deafened,
    );
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_app_event_Sse(
    RustStreamSink<AppEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_app_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_app_event(AppEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case AppEvent_Status(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_status_update(field0, serializer);
      case AppEvent_Users(serverId: final serverId, users: final users):
        sse_encode_i_32(1, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_list_ui_user(users, serializer);
      case AppEvent_Channels(
        serverId: final serverId,
        channels: final channels,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_list_ui_channel(channels, serializer);
      case AppEvent_Text(
        serverId: final serverId,
        from: final from,
        message: final message,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_String(from, serializer);
        sse_encode_String(message, serializer);
      case AppEvent_Stats(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_box_autoadd_ui_stats(field0, serializer);
      case AppEvent_InputLevel(
        levelDb: final levelDb,
        speaking: final speaking,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_f_32(levelDb, serializer);
        sse_encode_bool(speaking, serializer);
      case AppEvent_Certificate(
        serverId: final serverId,
        fingerprint: final fingerprint,
        changed: final changed,
      ):
        sse_encode_i_32(6, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_String(fingerprint, serializer);
        sse_encode_bool(changed, serializer);
      case AppEvent_Welcome(serverId: final serverId, text: final text):
        sse_encode_i_32(7, serializer);
        sse_encode_String(serverId, serializer);
        sse_encode_String(text, serializer);
    }
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_server_config(
    ServerConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_server_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_startup_options(
    StartupOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_startup_options(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_status_update(
    StatusUpdate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_status_update(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ui_stats(UiStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ui_stats(self, serializer);
  }

  @protected
  void sse_encode_conn_status(ConnStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_ui_channel(
    List<UiChannel> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ui_channel(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ui_user(List<UiUser> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ui_user(item, serializer);
    }
  }

  @protected
  void sse_encode_mic_mode(MicMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_noise_setting(NoiseSetting self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_server_config(ServerConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_opt_String(self.password, serializer);
    sse_encode_opt_String(self.certFingerprint, serializer);
  }

  @protected
  void sse_encode_startup_options(
    StartupOptions self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.storageDir, serializer);
    sse_encode_noise_setting(self.noise, serializer);
    sse_encode_mic_mode(self.micMode, serializer);
  }

  @protected
  void sse_encode_status_update(StatusUpdate self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.serverId, serializer);
    sse_encode_conn_status(self.status, serializer);
    sse_encode_String(self.detail, serializer);
    sse_encode_u_32(self.attempt, serializer);
    sse_encode_u_64(self.retryInMs, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_ui_channel(UiChannel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_box_autoadd_u_32(self.parent, serializer);
    sse_encode_String(self.description, serializer);
  }

  @protected
  void sse_encode_ui_stats(UiStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.serverId, serializer);
    sse_encode_f_32(self.tcpPingMs, serializer);
    sse_encode_f_32(self.udpPingMs, serializer);
    sse_encode_String(self.transport, serializer);
  }

  @protected
  void sse_encode_ui_user(UiUser self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.session, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.channelId, serializer);
    sse_encode_bool(self.talking, serializer);
    sse_encode_bool(self.muted, serializer);
    sse_encode_bool(self.deafened, serializer);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
