// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/mumbleway.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<AppEvent> dco_decode_StreamSink_app_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppEvent dco_decode_app_event(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  ServerConfig dco_decode_box_autoadd_server_config(dynamic raw);

  @protected
  StartupOptions dco_decode_box_autoadd_startup_options(dynamic raw);

  @protected
  StatusUpdate dco_decode_box_autoadd_status_update(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  UiSpectrum dco_decode_box_autoadd_ui_spectrum(dynamic raw);

  @protected
  UiStats dco_decode_box_autoadd_ui_stats(dynamic raw);

  @protected
  UiWaveform dco_decode_box_autoadd_ui_waveform(dynamic raw);

  @protected
  ConnStatus dco_decode_conn_status(dynamic raw);

  @protected
  DehissOption dco_decode_dehiss_option(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FeedbackGuardMode dco_decode_feedback_guard_mode(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ServerConfig> dco_decode_list_server_config(dynamic raw);

  @protected
  List<UiChannel> dco_decode_list_ui_channel(dynamic raw);

  @protected
  List<UiLogEntry> dco_decode_list_ui_log_entry(dynamic raw);

  @protected
  List<UiSpeakerLevel> dco_decode_list_ui_speaker_level(dynamic raw);

  @protected
  List<UiStage> dco_decode_list_ui_stage(dynamic raw);

  @protected
  List<UiStageCost> dco_decode_list_ui_stage_cost(dynamic raw);

  @protected
  List<UiUser> dco_decode_list_ui_user(dynamic raw);

  @protected
  MicMode dco_decode_mic_mode(dynamic raw);

  @protected
  NoiseSetting dco_decode_noise_setting(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  UiSpectrum? dco_decode_opt_box_autoadd_ui_spectrum(dynamic raw);

  @protected
  UiWaveform? dco_decode_opt_box_autoadd_ui_waveform(dynamic raw);

  @protected
  (String?, String?) dco_decode_record_opt_string_opt_string(dynamic raw);

  @protected
  (int, int, int) dco_decode_record_u_32_u_32_u_32(dynamic raw);

  @protected
  ServerConfig dco_decode_server_config(dynamic raw);

  @protected
  StageState dco_decode_stage_state(dynamic raw);

  @protected
  StartupOptions dco_decode_startup_options(dynamic raw);

  @protected
  StatusUpdate dco_decode_status_update(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UiChainStatus dco_decode_ui_chain_status(dynamic raw);

  @protected
  UiChannel dco_decode_ui_channel(dynamic raw);

  @protected
  UiDiagnostics dco_decode_ui_diagnostics(dynamic raw);

  @protected
  UiLogEntry dco_decode_ui_log_entry(dynamic raw);

  @protected
  UiProbe dco_decode_ui_probe(dynamic raw);

  @protected
  UiRecordingState dco_decode_ui_recording_state(dynamic raw);

  @protected
  UiServerStatus dco_decode_ui_server_status(dynamic raw);

  @protected
  UiSpeakerLevel dco_decode_ui_speaker_level(dynamic raw);

  @protected
  UiSpectrum dco_decode_ui_spectrum(dynamic raw);

  @protected
  UiStage dco_decode_ui_stage(dynamic raw);

  @protected
  UiStageCost dco_decode_ui_stage_cost(dynamic raw);

  @protected
  UiStageCosts dco_decode_ui_stage_costs(dynamic raw);

  @protected
  UiStats dco_decode_ui_stats(dynamic raw);

  @protected
  UiUser dco_decode_ui_user(dynamic raw);

  @protected
  UiWaveform dco_decode_ui_waveform(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<AppEvent> sse_decode_StreamSink_app_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppEvent sse_decode_app_event(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  ServerConfig sse_decode_box_autoadd_server_config(
    SseDeserializer deserializer,
  );

  @protected
  StartupOptions sse_decode_box_autoadd_startup_options(
    SseDeserializer deserializer,
  );

  @protected
  StatusUpdate sse_decode_box_autoadd_status_update(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UiSpectrum sse_decode_box_autoadd_ui_spectrum(SseDeserializer deserializer);

  @protected
  UiStats sse_decode_box_autoadd_ui_stats(SseDeserializer deserializer);

  @protected
  UiWaveform sse_decode_box_autoadd_ui_waveform(SseDeserializer deserializer);

  @protected
  ConnStatus sse_decode_conn_status(SseDeserializer deserializer);

  @protected
  DehissOption sse_decode_dehiss_option(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FeedbackGuardMode sse_decode_feedback_guard_mode(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ServerConfig> sse_decode_list_server_config(
    SseDeserializer deserializer,
  );

  @protected
  List<UiChannel> sse_decode_list_ui_channel(SseDeserializer deserializer);

  @protected
  List<UiLogEntry> sse_decode_list_ui_log_entry(SseDeserializer deserializer);

  @protected
  List<UiSpeakerLevel> sse_decode_list_ui_speaker_level(
    SseDeserializer deserializer,
  );

  @protected
  List<UiStage> sse_decode_list_ui_stage(SseDeserializer deserializer);

  @protected
  List<UiStageCost> sse_decode_list_ui_stage_cost(SseDeserializer deserializer);

  @protected
  List<UiUser> sse_decode_list_ui_user(SseDeserializer deserializer);

  @protected
  MicMode sse_decode_mic_mode(SseDeserializer deserializer);

  @protected
  NoiseSetting sse_decode_noise_setting(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UiSpectrum? sse_decode_opt_box_autoadd_ui_spectrum(
    SseDeserializer deserializer,
  );

  @protected
  UiWaveform? sse_decode_opt_box_autoadd_ui_waveform(
    SseDeserializer deserializer,
  );

  @protected
  (String?, String?) sse_decode_record_opt_string_opt_string(
    SseDeserializer deserializer,
  );

  @protected
  (int, int, int) sse_decode_record_u_32_u_32_u_32(
    SseDeserializer deserializer,
  );

  @protected
  ServerConfig sse_decode_server_config(SseDeserializer deserializer);

  @protected
  StageState sse_decode_stage_state(SseDeserializer deserializer);

  @protected
  StartupOptions sse_decode_startup_options(SseDeserializer deserializer);

  @protected
  StatusUpdate sse_decode_status_update(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UiChainStatus sse_decode_ui_chain_status(SseDeserializer deserializer);

  @protected
  UiChannel sse_decode_ui_channel(SseDeserializer deserializer);

  @protected
  UiDiagnostics sse_decode_ui_diagnostics(SseDeserializer deserializer);

  @protected
  UiLogEntry sse_decode_ui_log_entry(SseDeserializer deserializer);

  @protected
  UiProbe sse_decode_ui_probe(SseDeserializer deserializer);

  @protected
  UiRecordingState sse_decode_ui_recording_state(SseDeserializer deserializer);

  @protected
  UiServerStatus sse_decode_ui_server_status(SseDeserializer deserializer);

  @protected
  UiSpeakerLevel sse_decode_ui_speaker_level(SseDeserializer deserializer);

  @protected
  UiSpectrum sse_decode_ui_spectrum(SseDeserializer deserializer);

  @protected
  UiStage sse_decode_ui_stage(SseDeserializer deserializer);

  @protected
  UiStageCost sse_decode_ui_stage_cost(SseDeserializer deserializer);

  @protected
  UiStageCosts sse_decode_ui_stage_costs(SseDeserializer deserializer);

  @protected
  UiStats sse_decode_ui_stats(SseDeserializer deserializer);

  @protected
  UiUser sse_decode_ui_user(SseDeserializer deserializer);

  @protected
  UiWaveform sse_decode_ui_waveform(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_app_event_Sse(
    RustStreamSink<AppEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_event(AppEvent self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_server_config(
    ServerConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_startup_options(
    StartupOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_status_update(
    StatusUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ui_spectrum(
    UiSpectrum self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_stats(UiStats self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ui_waveform(
    UiWaveform self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conn_status(ConnStatus self, SseSerializer serializer);

  @protected
  void sse_encode_dehiss_option(DehissOption self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_feedback_guard_mode(
    FeedbackGuardMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_server_config(
    List<ServerConfig> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_channel(
    List<UiChannel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_log_entry(
    List<UiLogEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_speaker_level(
    List<UiSpeakerLevel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_stage(List<UiStage> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ui_stage_cost(
    List<UiStageCost> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ui_user(List<UiUser> self, SseSerializer serializer);

  @protected
  void sse_encode_mic_mode(MicMode self, SseSerializer serializer);

  @protected
  void sse_encode_noise_setting(NoiseSetting self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ui_spectrum(
    UiSpectrum? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ui_waveform(
    UiWaveform? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_opt_string_opt_string(
    (String?, String?) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_u_32_u_32(
    (int, int, int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_server_config(ServerConfig self, SseSerializer serializer);

  @protected
  void sse_encode_stage_state(StageState self, SseSerializer serializer);

  @protected
  void sse_encode_startup_options(
    StartupOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_status_update(StatusUpdate self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_ui_chain_status(UiChainStatus self, SseSerializer serializer);

  @protected
  void sse_encode_ui_channel(UiChannel self, SseSerializer serializer);

  @protected
  void sse_encode_ui_diagnostics(UiDiagnostics self, SseSerializer serializer);

  @protected
  void sse_encode_ui_log_entry(UiLogEntry self, SseSerializer serializer);

  @protected
  void sse_encode_ui_probe(UiProbe self, SseSerializer serializer);

  @protected
  void sse_encode_ui_recording_state(
    UiRecordingState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_server_status(
    UiServerStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_speaker_level(
    UiSpeakerLevel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ui_spectrum(UiSpectrum self, SseSerializer serializer);

  @protected
  void sse_encode_ui_stage(UiStage self, SseSerializer serializer);

  @protected
  void sse_encode_ui_stage_cost(UiStageCost self, SseSerializer serializer);

  @protected
  void sse_encode_ui_stage_costs(UiStageCosts self, SseSerializer serializer);

  @protected
  void sse_encode_ui_stats(UiStats self, SseSerializer serializer);

  @protected
  void sse_encode_ui_user(UiUser self, SseSerializer serializer);

  @protected
  void sse_encode_ui_waveform(UiWaveform self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
