import 'dart:async';

import 'package:flutter/foundation.dart' show ValueListenable;
import 'package:flutter/material.dart';

import '../l10n/app_localizations.dart';
import '../services/background_classifier.dart';
import '../services/noise_profiles.dart';
import '../src/rust/api/mumbleway.dart';
import '../state/app_state.dart';
import 'gate_indicators.dart';
import '../theme.dart';

/// Live view of what the capture chain is doing to the rider's voice.
///
/// Three spectra taken from the same block — the microphone, what the noise
/// gate was about to judge, and what reached the encoder — over a row of dots
/// saying where each stage of the chain stands.
///
/// **Mount this only while it is on screen.** Asking the engine for a frame is
/// what makes it compute one; the ask expires half a second later, so a widget
/// that is not built costs nothing at all, in the core as well as here. The
/// diagnostics panel is never disposed — it is only slid off screen — so this
/// has to be created and destroyed by an `if`, not merely hidden.
///
/// **Driven by a [Timer], and it used to be a [Ticker].** The ticker was chosen
/// for a real property — Flutter mutes tickers in the background, so
/// backgrounding stopped the polling and let the engine's arming lapse with no
/// code of its own to get wrong — and it cost more than it was worth.
///
/// A ticker asks for a frame *every vsync*, which is what it is for. This one
/// wanted 20 Hz and got 60 or 120, discarding two frames in three; but the ask
/// is not free, because a running ticker keeps the whole frame pipeline turning
/// over for as long as the panel is open. Opening diagnostics on an idle,
/// disconnected app took this machine's GPU from ~0% to ~29%, and the analyser
/// is the largest continuously-repainted thing on that panel.
///
/// The background behaviour is now explicit instead of inherited, via
/// [AppLifecycleListener] — which says what it means, and does not depend on
/// noticing that a ticker was load-bearing for something other than animation.
class SpectrumView extends StatefulWidget {
  const SpectrumView({super.key});

  @override
  State<SpectrumView> createState() => _SpectrumViewState();
}

class _SpectrumViewState extends State<SpectrumView> {
  Timer? _poll;
  AppLifecycleListener? _lifecycle;

  /// One notifier per thing that changes at its own rate, rather than one
  /// `setState` for all of them.
  ///
  /// **The analyser moves twenty times a second and the dots move on a flip.**
  /// A single `setState` on the tick rebuilt both, so eleven dots, three
  /// classifier rows, two paragraphs of wrapped text and the effort line were
  /// laid out afresh twenty times a second to draw exactly what they drew
  /// last time — on the phones least able to afford it, since this panel is
  /// open precisely when something is wrong.
  ///
  /// Split this way each part rebuilds when *its own* data changes: the
  /// spectrum every frame, because that is the point of it, and everything
  /// below it when the chain actually moves.
  final _spectrum = ValueNotifier<UiSpectrum?>(null);
  final _chain = ValueNotifier<UiChainStatus?>(null);

  /// Derived, and separate, because they are what the cheap widgets watch.
  /// A `ValueNotifier` is silent when the value is unchanged, so a bool that
  /// flips twice a minute costs two rebuilds a minute.
  final _transmitting = ValueNotifier<bool>(false);
  final _stalledNow = ValueNotifier<bool>(false);

  /// What the gauges beside the analyser draw.
  ///
  /// Its own notifier, holding a value with a real `==`, for the same reason
  /// the chain signature exists: `UiChainStatus` is rebuilt by the bridge on
  /// every poll and is never equal to the last one, so watching it directly
  /// would repaint the gauges twenty times a second to draw the same picture.
  /// [`GateSnapshot`] rounds each number to what a bar a few dozen pixels tall
  /// can actually show, so a reading that jitters in the last digit is silent.
  final _gate = ValueNotifier<GateSnapshot?>(null);

  /// What the chain row and the lines under it actually draw.
  ///
  /// Compared instead of the status itself: `UiChainStatus` is regenerated by
  /// the bridge on every poll and carries a fresh `List<UiStage>`, so it is
  /// never equal to the last one however little has changed. This is the
  /// picture, and when the picture is the same nothing below is rebuilt.
  String _chainSignature = '';

  /// The last frame counter seen. A u64 in the core, so a BigInt here.
  BigInt? _lastSeq;
  int _sinceNewFrame = 0;

  /// 20 Hz. Faster buys nothing: the core smooths the bands at 33 Hz and an eye
  /// cannot follow either.
  ///
  /// A period rather than a count of frames. It was `if (++_tick % 3 != 0)
  /// return`, which is 20 Hz only on a 60 Hz screen — on a 120 Hz one it was
  /// 40, so the devices with the most headroom were asked to do twice the work
  /// to draw the same picture, and the bridge was crossed twice as often for a
  /// spectrum the core had not recomputed.
  static const _pollEvery = Duration(milliseconds: 50);

  @override
  void initState() {
    super.initState();
    _start();
    // What the ticker gave for free, said out loud. A backgrounded app must
    // stop asking for spectra: the ask is what makes the core compute them,
    // and it expires half a second after the last one.
    _lifecycle = AppLifecycleListener(
      onStateChange: (s) =>
          s == AppLifecycleState.resumed ? _start() : _stop(),
    );
  }

  void _start() {
    _poll ??= Timer.periodic(_pollEvery, (_) => _onTick());
  }

  void _stop() {
    _poll?.cancel();
    _poll = null;
  }

  @override
  void dispose() {
    _stop();
    _lifecycle?.dispose();
    _spectrum.dispose();
    _chain.dispose();
    _transmitting.dispose();
    _stalledNow.dispose();
    _gate.dispose();
    super.dispose();
  }

  /// Everything the widgets below the analyser read, in one comparable string.
  ///
  /// Deliberately not every field of the status — the level, the floor and the
  /// peak all move every block and none of them is drawn here; including them
  /// would rebuild the dots twenty times a second again, which is the whole
  /// thing being avoided.
  static String _signature(UiChainStatus? c, {required bool frozen}) {
    if (c == null) return '';
    final b = StringBuffer()
      ..write(c.effectiveProfile.index)
      ..write('/')
      // Moves only at a speech onset, so this costs nothing at rest — and
      // without it the number beside the profile would stay at whatever it
      // read when some *other* field last changed.
      ..write(c.autoSnrDb?.round())
      ..write('/')
      ..write(c.enhancerEffort)
      ..write('/')
      // Without this the row would not repaint when the model changed, which
      // is the whole point of adding it.
      ..write(c.enhancerSimpleModel ? 'S' : 'F')
      ..write('/')
      ..write(c.relief)
      ..write('/')
      ..writeAll(c.disabledStages, ',')
      ..write('/');
    // **The rung above always stays in.** Freezing the dots must not freeze
    // the warnings, or the rung that stops them following the audio would also
    // hide the rung after it — and the last one is the enhancer being switched
    // off, which is the single thing a rider most needs to see.
    if (!frozen) {
      for (final s in c.stages) {
        b
          ..write(s.id)
          ..write(s.state.index)
          ..write(';');
      }
    }
    return b.toString();
  }

  void _onTick() {
    UiSpectrum? spectrum;
    UiChainStatus? chain;
    try {
      // The chain status is free and always current, so it is read first — it
      // is what says whether the analyser is still allowed to run.
      chain = audioChainStatus();
      // **Not calling this is how the engine stops.** The ask is what makes
      // the transforms happen, and it expires by itself half a second later,
      // so a rung that gives the analyser up simply stops asking. The core
      // refuses as well, and both matter: the core's refusal saves the
      // transforms, and this saves the bridge crossing and the repaint.
      spectrum = chain.analyserDisabled ? null : audioSpectrum();
    } catch (_) {
      // The engine is not up. Nothing to draw, and nothing to complain about.
      spectrum = null;
      chain = null;
    }

    // A frame counter that has stopped moving means the worker has stopped —
    // the devices are shut, most likely — which looks exactly like silence if
    // the last frame is left on screen.
    if (spectrum != null && spectrum.seq == _lastSeq) {
      _sinceNewFrame++;
    } else {
      _sinceNewFrame = 0;
      _lastSeq = spectrum?.seq;
    }

    if (!mounted) return;
    // No `setState` at all. Each notifier wakes only what reads it, and the
    // three below stay silent unless their value actually moved.
    _spectrum.value = spectrum;
    _stalledNow.value = _sinceNewFrame > 20;
    _transmitting.value = spectrum?.transmitting ?? false;
    _gate.value = chain == null
        ? null
        : GateSnapshot(
            levelDb: chain.levelDb,
            noiseFloorDb: chain.noiseFloorDb,
            opensAtDb: chain.activationThresholdDb,
            harmonicity: chain.harmonicity,
            autoSnrDb: chain.autoSnrDb,
            autoHelmetBelowDb: chain.autoSnrHelmetBelowDb,
            autoStandardBelowDb: chain.autoSnrStandardBelowDb,
            voicedThreshold: chain.voicedThreshold,
            floorHeld: chain.floorHeld,
            // Nothing to measure against with suppression off — there is no
            // tracked floor and no margin — and nothing trustworthy during
            // warm-up, when the tracker has not settled. Both draw as
            // unavailable rather than as a confident zero.
            applicable: !chain.warmingUp &&
                chain.effectiveProfile != NoiseSetting.off,
          );

    final signature = _signature(chain, frozen: _dotsFrozen);
    if (signature != _chainSignature) {
      _chainSignature = signature;
      _chain.value = chain;
    }
  }

  /// Whether the dots are still allowed to follow the audio.
  ///
  /// Read from the last published status rather than the incoming one, so the
  /// rung that switches this off does not also switch off the update that
  /// would have shown it happening.
  bool get _dotsFrozen => _chain.value?.liveDotsDisabled ?? false;

  /// **Reads no changing state itself**, so this method runs once and the
  /// pieces below it update independently. In particular it must not touch
  /// `AppStateScope`: that is an `InheritedNotifier`, and depending on it here
  /// would rebuild the whole panel on every app-state change — a ping, a
  /// meter, a roster update — on top of the twenty ticks a second.
  @override
  Widget build(BuildContext context) {
    final l = L.of(context);
    final scheme = Theme.of(context).colorScheme;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          l.diagSpectrum,
          style: TextStyle(
            fontSize: 10,
            fontWeight: FontWeight.w700,
            letterSpacing: 0.8,
            color: scheme.onSurfaceVariant,
          ),
        ),
        const SizedBox(height: 8),
        _LegendBar(transmitting: _transmitting),
        const SizedBox(height: 6),
        // The one thing that genuinely redraws every frame, and the boundary
        // that keeps that from dirtying everything beside it: without it the
        // whole column shares a layer, so an analyser repaint repaints the
        // dots, the text and the warnings too.
        RepaintBoundary(
          child: SizedBox(
            height: 120,
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Expanded(
                  child: ValueListenableBuilder<UiChainStatus?>(
                    valueListenable: _chain,
                    builder: (context, chain, child) =>
                        (chain?.analyserDisabled ?? false)
                        ? const _AnalyserGivenUp()
                        : child!,
                    child: _SpectrumBody(
                      spectrum: _spectrum,
                      stalled: _stalledNow,
                      chain: _chain,
                    ),
                  ),
                ),
                const SizedBox(width: 8),
                // **Inside the same `SizedBox`, so the two are the same height
                // by construction** rather than by two numbers that agree until
                // somebody changes one. The gauges share the analyser's dBFS
                // axis, and an axis that is the same scale but a different
                // height would be worse than no shared axis at all.
                //
                // Its own listenable, and a cheap one: the gauges move with the
                // audio while everything else in this panel moves when the
                // chain does, so they must not drag the rest along at 20 Hz.
                // The bottom of the axis comes from the spectrum frame, because
                // that is where the analyser gets it — a constant here would be
                // right only until the other one changed.
                RepaintBoundary(
                  child: ValueListenableBuilder<UiSpectrum?>(
                    valueListenable: _spectrum,
                    builder: (context, frame, _) =>
                        ValueListenableBuilder<GateSnapshot?>(
                      valueListenable: _gate,
                      builder: (context, gate, _) => GateIndicators(
                        snapshot: gate,
                        floorDb: frame?.floorDb ?? -90,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
        const SizedBox(height: 10),
        ValueListenableBuilder<UiChainStatus?>(
          valueListenable: _chain,
          builder: (context, chain, _) => Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Above the dots, because it is the setting they are all
              // measured under. See [_AutoProfile] for why this is no longer
              // limited to Auto.
              if (chain != null)
                _AutoProfile(
                  profile: chain.effectiveProfile,
                  snrDb: chain.autoSnrDb,
                  automatic:
                      AppStateScope.of(context).noise == NoiseSetting.auto,
                  // Only meaningful under Auto: a profile chosen by hand was
                  // never going to change, so calling it pinned would be
                  // reporting a loss that did not happen.
                  pinned:
                      AppStateScope.of(context).noise == NoiseSetting.auto &&
                      chain.classifierDisabled,
                ),
              // Directly under it, because it is the evidence behind it. The
              // classifier only runs under Auto, so this appears and
              // disappears with the line above without needing the condition
              // repeated.
              //
              // Inside this builder and still updating on its own: it depends
              // on `AppStateScope` itself, so the classifier's two-second tick
              // rebuilds it directly rather than waiting for the chain to
              // move.
              //
              // Given up one rung after the analyser. The model keeps running
              // — `Auto` reads its verdict and the profile depends on it — so
              // this is the three rows of display and nothing else.
              if (!(chain?.classifierTopDisabled ?? false))
                // ignore: prefer_const_constructors
                _ClassifierTop(),
              if (chain != null) _ChainDots(status: chain),
              if (chain != null) _EnhancerEffort(status: chain),
              // Not `const`: it reads the classifier's state, and a const
              // child would be built once and never notice the model starting.
              // ignore: prefer_const_constructors
              _ClassifierNote(),
            ],
          ),
        ),
      ],
    );
  }
}

/// Stands where the analyser was, once the ladder has given it up.
///
/// **The analyser is the most expensive thing on this panel** — three
/// transforms per third block in the core and a continuously repainting canvas
/// above them — so on a device that cannot return a block inside 10 ms it is
/// the last diagnostic worth keeping and the first one worth spending. A blank
/// box would read as a broken analyser, which is the one thing it must not:
/// the analyser is what a rider opens this panel to look at.
class _AnalyserGivenUp extends StatelessWidget {
  const _AnalyserGivenUp();

  @override
  Widget build(BuildContext context) {
    final l = L.of(context);
    return Container(
      alignment: Alignment.center,
      padding: const EdgeInsets.symmetric(horizontal: 16),
      decoration: BoxDecoration(
        border: Border.all(
          color: StatusColors.connecting.withValues(alpha: 0.4),
        ),
        borderRadius: BorderRadius.circular(6),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(
            Icons.warning_amber_rounded,
            size: 16,
            color: StatusColors.connecting,
          ),
          const SizedBox(width: 8),
          Flexible(
            child: Text(
              l.diagAnalyserGivenUp,
              style: TextStyle(
                fontSize: 11,
                color: StatusColors.connecting,
                height: 1.35,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

/// The legend, which changes only when the sent trace changes meaning.
///
/// Split out so that reading `anyLive` — an `AppStateScope` dependency — wakes
/// three coloured keys rather than the whole panel.
class _LegendBar extends StatelessWidget {
  const _LegendBar({required this.transmitting});

  final ValueListenable<bool> transmitting;

  @override
  Widget build(BuildContext context) {
    // Green means it reached somebody, so it needs both halves: the chain
    // decided to send, and there is a live session for it to go to.
    final live = AppStateScope.of(context).anyLive;
    return ValueListenableBuilder<bool>(
      valueListenable: transmitting,
      builder: (context, sending, _) => _Legend(transmitting: sending && live),
    );
  }
}

/// The analyser itself, and the two states that stand in for it.
class _SpectrumBody extends StatelessWidget {
  const _SpectrumBody({
    required this.spectrum,
    required this.stalled,
    required this.chain,
  });

  final ValueListenable<UiSpectrum?> spectrum;
  final ValueListenable<bool> stalled;

  /// Read for the two gate levels drawn across the amplitude axis.
  ///
  /// The numbers were already in the panel — the noise floor and the level a
  /// block has to beat — but as figures in a column a long way from the trace
  /// they describe. "Is this loud enough to be sent?" is a comparison, and a
  /// comparison between a picture and a number several inches away is one the
  /// reader has to do in their head.
  final ValueListenable<UiChainStatus?> chain;

  @override
  Widget build(BuildContext context) {
    final l = L.of(context);
    final scheme = Theme.of(context).colorScheme;
    final live = AppStateScope.of(context).anyLive;
    return ValueListenableBuilder<bool>(
      valueListenable: stalled,
      builder: (context, isStalled, _) => ValueListenableBuilder<UiSpectrum?>(
        valueListenable: spectrum,
        builder: (context, frame, _) => (frame == null || isStalled)
            ? _Idle(
                message: isStalled
                    ? l.diagSpectrumStalled
                    : l.diagSpectrumWaiting,
              )
            : ValueListenableBuilder<UiChainStatus?>(
                valueListenable: chain,
                builder: (context, status, _) => CustomPaint(
                  size: Size.infinite,
                  painter: _SpectrumPainter(
                    spectrum: frame,
                    sending: frame.transmitting && live,
                    grid: scheme.onSurfaceVariant.withValues(alpha: 0.16),
                    raw: scheme.onSurfaceVariant.withValues(alpha: 0.55),
                    preGate: scheme.primary,
                    // Only while the chain is telling the truth. During warm-up
                    // the floor tracker has not settled, so a mark drawn then
                    // would be a confident line in the wrong place.
                    noiseFloorDb: (status == null || status.warmingUp)
                        ? null
                        : status.noiseFloorDb,
                    opensAtDb: (status == null || status.warmingUp)
                        ? null
                        : status.activationThresholdDb,
                    floorLabel: L.of(context).diagPlotFloor,
                    opensAtLabel: L.of(context).diagPlotOpensAt,
                  ),
                ),
              ),
      ),
    );
  }
}

/// Says when the classifier is running without an accelerator behind it.
///
/// **A note, not a failure**, and it reports rather than warns. The same model
/// and runtime were timed at 2.4 ms an inference on a Mac, which at one every
/// two seconds is a tenth of a percent of a core — so an earlier draft of this
/// widget, which told riders it "costs battery on a long ride", was overstating
/// a cost nobody had measured. It now shows the number from *this* device.
///
/// What it claims is deliberately narrow: *the accelerated path was not
/// built*. Core ML decides per operation whether to use the Neural Engine, the
/// GPU or the CPU and reports none of it, so "an NPU is doing this" is not
/// something the app can honestly say — only that it asked and was refused.
class _ClassifierNote extends StatelessWidget {
  const _ClassifierNote();

  @override
  Widget build(BuildContext context) {
    final l = L.of(context);
    final classifier = AppStateScope.of(context).classifier;
    // Two things to explain, and a grey dot explains neither on its own.
    final String message;
    if (!BackgroundClassifier.supportedHere) {
      message = l.diagClassifierUnavailable;
    } else if (classifier.onCpuOnly) {
      // The cost, measured here, rather than an adjective. An earlier draft
      // said it "costs battery on a long ride"; then the same model and
      // runtime were timed at 2.4 ms an inference, which at one every two
      // seconds is a tenth of a percent of a core. Saying a number lets a
      // rider on a slow phone see a big one and a rider on a fast one see the
      // truth, instead of both reading the same warning.
      message = l.diagClassifierOnCpu(
        classifier.lastInferenceMs.toStringAsFixed(0),
      );
    } else {
      return const SizedBox.shrink();
    }
    final scheme = Theme.of(context).colorScheme;
    return Padding(
      padding: const EdgeInsets.only(top: 10),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(
            Icons.warning_amber_rounded,
            size: 15,
            color: StatusColors.connecting,
          ),
          const SizedBox(width: 6),
          Expanded(
            child: Text(
              message,
              style: TextStyle(fontSize: 11, color: scheme.onSurfaceVariant),
            ),
          ),
        ],
      ),
    );
  }
}

/// Says when the speech enhancer is not running at full effort.
///
/// **Required on every platform, not only where it happens.** A rider
/// comparing two phones has no way to tell why one sounds different: the
/// enhancer steps itself down when a device cannot return a frame inside
/// 10 ms, and afterwards every other number on this panel reads the same. An
/// amber dot says something changed; this says what, and it is the one line a
/// support conversation actually needs.
///
/// **The rung is always named, including at full effort.** An earlier version
/// showed nothing while the enhancer was coping, reasoning that a note saying
/// "working normally" on every device teaches people to stop reading the
/// panel. That reasoning is right about *prose* and wrong about *state*: a
/// diagnostics panel is read to find out what the chain is doing, and a rider
/// who cannot see the rung cannot tell a device running at full effort from
/// one whose ladder has not been built into the version they installed.
///
/// So the rung is a value beside a label, the way `Auto is using Helmet` is —
/// and the sentence explaining *why* it stepped down still appears only when
/// it has.
class _EnhancerEffort extends StatelessWidget {
  const _EnhancerEffort({required this.status});

  final UiChainStatus status;

  @override
  Widget build(BuildContext context) {
    final l = L.of(context);
    final scheme = Theme.of(context).colorScheme;
    final effort = status.enhancerEffort;

    final name = switch (effort) {
      1 => l.diagEnhancerRungReduced,
      2 => l.diagEnhancerRungLight,
      3 => l.diagEnhancerRungOff,
      _ => l.diagEnhancerRungFull,
    };
    // Amber once it has given something up, red when it has given up
    // everything, and the ordinary text colour while it is coping — so the
    // row is legible at a glance without shouting on a device that is fine.
    final colour = switch (effort) {
      0 => null,
      3 => StatusColors.failed,
      _ => StatusColors.connecting,
    };
    final why = switch (effort) {
      1 => l.diagEnhancerReduced,
      2 => l.diagEnhancerErbOnly,
      3 => l.diagEnhancerBypassed,
      _ => null,
    };

    return Padding(
      padding: const EdgeInsets.only(top: 10),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(
                Icons.speed,
                size: 14,
                color: colour ?? scheme.onSurfaceVariant,
              ),
              const SizedBox(width: 6),
              Text(
                l.diagEnhancerEffort,
                style: TextStyle(fontSize: 12, color: scheme.onSurfaceVariant),
              ),
              const SizedBox(width: 6),
              Text(
                name,
                style: TextStyle(
                  fontSize: 12,
                  fontWeight: FontWeight.w700,
                  color: colour,
                ),
              ),
            ],
          ),
          // Which model, under which rung.
          //
          // **The rung alone could not answer the question a rider asks.**
          // `Full`, `Reduced` and `Light` are stages *within* whichever model
          // is loaded, so a phone on the cheap model at full effort read
          // identically to one on the expensive model at full effort — and
          // "Light" here is a different thing from the "Light noise model"
          // setting, which made the pair worse than silent. Toggling that
          // setting now changes something visible.
          //
          // Shown on both values rather than only when it is cheap: this is a
          // state and not a warning, and a rider who cannot see "Full" cannot
          // tell a phone running the expensive model from a build too old to
          // have the row. Same argument as the rung itself.
          Padding(
            padding: const EdgeInsets.only(top: 4, left: 20),
            child: Row(
              children: [
                Text(
                  l.diagEnhancerModel,
                  style: TextStyle(
                    fontSize: 11,
                    color: scheme.onSurfaceVariant,
                  ),
                ),
                const SizedBox(width: 6),
                Text(
                  status.enhancerSimpleModel
                      ? l.diagEnhancerModelSimple
                      : l.diagEnhancerModelFull,
                  style: TextStyle(
                    fontSize: 11,
                    fontWeight: FontWeight.w700,
                    // Amber when it is the cheap one: it is a real reduction
                    // in what the chain can do, whether a rider chose it, the
                    // ladder reached it, or the device has one core.
                    color: status.enhancerSimpleModel
                        ? StatusColors.connecting
                        : scheme.onSurfaceVariant,
                  ),
                ),
              ],
            ),
          ),
          if (why != null)
            Padding(
              padding: const EdgeInsets.only(top: 4, left: 20),
              child: Text(
                why,
                style: TextStyle(fontSize: 11, color: scheme.onSurfaceVariant),
              ),
            ),
          // The whole-chain warning, once, under the rung it belongs to.
          //
          // **Separate from the rung line on purpose.** The rung is a fact
          // about one stage; this is the consequence for the rider, and it is
          // the only place the app says out loud that the sound is worse than
          // the app can otherwise make it. It names a device rather than a
          // setting because there is no setting — the ladder is not a
          // preference and cannot be turned off.
          //
          // Two wordings, because the ladder bends the enhancer before it
          // switches anything off: for the first two rungs there is nothing
          // crossed out above, and a message that says there is sends a reader
          // hunting for something that is not there.
          if (status.relief > 0)
            Padding(
              padding: const EdgeInsets.only(top: 10),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Icon(
                    Icons.warning_amber_rounded,
                    size: 15,
                    color: StatusColors.connecting,
                  ),
                  const SizedBox(width: 6),
                  Expanded(
                    child: Text(
                      status.disabledStages.isEmpty
                          ? l.diagChainReduced
                          : l.diagChainDegraded,
                      style: TextStyle(
                        fontSize: 11,
                        color: scheme.onSurfaceVariant,
                      ),
                    ),
                  ),
                ],
              ),
            ),
        ],
      ),
    );
  }
}

/// What the classifier is actually hearing, three classes at a time.
///
/// **The chain reads one of these 521 numbers and ignores the other 520.** A
/// bare "Music 0.83" cannot say whether the model heard a stereo, a motorway or
/// a hairdryer, so a profile switch that surprises a rider has no explanation
/// available. The other two rows are that explanation — and they are how the
/// `Music` class was understood in the first place, when an engine at speed
/// turned out to score 0.969 on it and was read as a false positive until it
/// was not.
///
/// `Music` is drawn in the transmitted green once it is over the bar, so the
/// row that decides is the row that stands out — and a reader can see the
/// moment the decision flips rather than inferring it from the profile
/// changing a beat later.
class _ClassifierTop extends StatelessWidget {
  const _ClassifierTop();

  @override
  Widget build(BuildContext context) {
    final l = L.of(context);
    final classifier = AppStateScope.of(context).classifier;
    final top = classifier.top;
    final scheme = Theme.of(context).colorScheme;

    if (top.isEmpty) {
      // **An empty list has to say why it is empty.** The model runs only
      // under Automatic, and only while the devices are open — so a rider who
      // opens the panel between calls sees nothing here, which is
      // indistinguishable from a version that never had this. One line beats
      // a silence that reads as a missing feature.
      if (!classifier.running) return const SizedBox.shrink();
      return Padding(
        padding: const EdgeInsets.only(bottom: 10),
        child: Row(
          children: [
            SizedBox(
              width: 11,
              height: 11,
              child: CircularProgressIndicator(
                strokeWidth: 1.6,
                color: scheme.onSurfaceVariant,
              ),
            ),
            const SizedBox(width: 8),
            Text(
              l.diagClassifierListening,
              style: TextStyle(fontSize: 11, color: scheme.onSurfaceVariant),
            ),
          ],
        ),
      );
    }

    return Padding(
      padding: const EdgeInsets.only(bottom: 10),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          for (final c in top)
            Padding(
              padding: const EdgeInsets.only(bottom: 3),
              child: _ClassRow(
                score: c,
                deciding: c.label == 'Music',
                over: c.score >= BackgroundClassifier.bar,
                muted: scheme.onSurfaceVariant,
              ),
            ),
        ],
      ),
    );
  }
}

class _ClassRow extends StatelessWidget {
  const _ClassRow({
    required this.score,
    required this.deciding,
    required this.over,
    required this.muted,
  });

  final ClassScore score;
  final bool deciding, over;
  final Color muted;

  @override
  Widget build(BuildContext context) {
    final colour = deciding && over ? StatusColors.connected : muted;
    return Row(
      children: [
        SizedBox(
          width: 108,
          child: Text(
            score.label,
            overflow: TextOverflow.ellipsis,
            style: TextStyle(
              fontSize: 11,
              color: colour,
              fontWeight: deciding ? FontWeight.w700 : FontWeight.w400,
            ),
          ),
        ),
        const SizedBox(width: 6),
        // A bar as well as a number. Three scores are read against each other
        // — whether the top one is far ahead or the field is level is the
        // whole of what this says — and that comparison is a glance at bar
        // lengths rather than three subtractions.
        Expanded(
          child: ClipRRect(
            borderRadius: BorderRadius.circular(2),
            child: LinearProgressIndicator(
              value: score.score.clamp(0.0, 1.0),
              minHeight: 4,
              backgroundColor: muted.withValues(alpha: 0.16),
              valueColor: AlwaysStoppedAnimation(colour),
            ),
          ),
        ),
        const SizedBox(width: 6),
        SizedBox(
          width: 30,
          child: Text(
            score.score.toStringAsFixed(2),
            textAlign: TextAlign.right,
            style: TextStyle(
              fontSize: 11,
              color: colour,
              fontFeatures: const [FontFeature.tabularFigures()],
            ),
          ),
        ),
      ],
    );
  }
}

/// Where Auto has landed, as a name.
/// Which noise profile the chain is running under, however it was arrived at.
///
/// **Shown for all five settings, not only `Auto`.** It used to appear only
/// under `Auto`, on the reasoning that the other four would just repeat a
/// choice the rider had already made. That reasoning does not survive contact:
/// the panel is read when something sounds wrong, often on a device somebody
/// else configured or that was set months ago, and "which profile is this even
/// running?" is then the first question. Repeating an answer costs one line;
/// withholding it sent three separate reports that the profile line was
/// missing, when in every case the profile was simply set by hand.
///
/// The wording distinguishes the two, because *how* it was chosen matters:
/// under `Auto` the name is a live verdict that can change mid-ride, and by
/// hand it is an instruction that will not.
class _AutoProfile extends StatelessWidget {
  const _AutoProfile({
    required this.profile,
    required this.automatic,
    this.snrDb,
    this.pinned = false,
  });

  final NoiseSetting profile;

  /// The onset SNR `Auto` chose this profile from, in dB.
  ///
  /// **The evidence, next to the verdict.** The profile alone says what
  /// happened; a rider whose Auto sits on `Helmet` in a quiet room can see that
  /// it did and nothing about why. With the number, a wrong profile splits into
  /// two different faults that need different fixes — the chain measured the
  /// room wrongly, or it read a correct measurement wrongly.
  ///
  /// Null until the first phrase, and always null when the profile was set by
  /// hand: nothing was chosen from anything, and showing a stale measurement
  /// beside a fixed setting would imply a connection that is not there.
  final double? snrDb;

  /// Whether `Auto` picked this, rather than the rider.
  final bool automatic;

  /// `Auto` is chosen, but the ladder has stopped the classifier — so this
  /// profile can no longer change and is stuck where it stood.
  ///
  /// Worth saying out loud rather than leaving the line looking normal: the
  /// rider asked for a setting that adapts, and it has quietly stopped
  /// adapting. Everything else on the panel reads exactly as it did before.
  final bool pinned;

  @override
  Widget build(BuildContext context) {
    final l = L.of(context);
    final scheme = Theme.of(context).colorScheme;
    return Padding(
      padding: const EdgeInsets.only(bottom: 10),
      child: Row(
        children: [
          Icon(
            automatic ? Icons.auto_mode : Icons.tune,
            size: 14,
            color: scheme.onSurfaceVariant,
          ),
          const SizedBox(width: 6),
          Text(
            automatic ? l.diagAutoProfile : l.diagChosenProfile,
            style: TextStyle(fontSize: 12, color: scheme.onSurfaceVariant),
          ),
          const SizedBox(width: 6),
          Text(
            noiseProfileTitle(l, profile),
            style: TextStyle(
              fontSize: 12,
              fontWeight: FontWeight.w700,
              // Amber, in the same vocabulary the rest of the panel uses for
              // "this device gave something up".
              color: pinned ? StatusColors.connecting : null,
            ),
          ),
          // Grey and in brackets, like the pinned note below: it qualifies
          // the profile rather than competing with it. Whole decibels — the
          // thresholds are 20 dB apart and a decimal would imply a precision
          // the measurement does not have.
          if (snrDb != null) ...[
            const SizedBox(width: 5),
            Text(
              l.diagAutoSnr(snrDb!.round()),
              style: TextStyle(
                fontSize: 11,
                color: scheme.onSurfaceVariant,
                fontFeatures: const [FontFeature.tabularFigures()],
              ),
            ),
          ],
          if (pinned) ...[
            const SizedBox(width: 5),
            // Grey and in brackets: it qualifies the name rather than
            // competing with it, and the name is what is being read.
            Text(
              l.diagProfilePinned,
              style: TextStyle(fontSize: 11, color: scheme.onSurfaceVariant),
            ),
          ],
        ],
      ),
    );
  }
}

/// Says which trace is which, and what the sent trace's colour means.
class _Legend extends StatelessWidget {
  const _Legend({required this.transmitting});

  final bool transmitting;

  @override
  Widget build(BuildContext context) {
    final l = L.of(context);
    final scheme = Theme.of(context).colorScheme;
    return Wrap(
      spacing: 14,
      runSpacing: 4,
      children: [
        _key(scheme.onSurfaceVariant.withValues(alpha: 0.55), l.diagTraceRaw, context),
        _key(scheme.primary, l.diagTracePreGate, context),
        _key(
          _SpectrumPainter.sentColour(transmitting),
          transmitting ? l.diagTraceSentLive : l.diagTraceSentIdle,
          context,
        ),
      ],
    );
  }

  Widget _key(Color colour, String label, BuildContext context) => Row(
    mainAxisSize: MainAxisSize.min,
    children: [
      Container(width: 8, height: 8, color: colour),
      const SizedBox(width: 5),
      Text(
        label,
        style: TextStyle(
          fontSize: 10,
          color: Theme.of(context).colorScheme.onSurfaceVariant,
        ),
      ),
    ],
  );
}

/// Shown instead of a frozen picture when there is nothing live to draw.
class _Idle extends StatelessWidget {
  const _Idle({required this.message});

  final String message;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    return DecoratedBox(
      decoration: BoxDecoration(
        border: Border.all(color: scheme.onSurfaceVariant.withValues(alpha: 0.16)),
        borderRadius: BorderRadius.circular(4),
      ),
      child: Center(
        child: Text(
          message,
          style: TextStyle(fontSize: 11, color: scheme.onSurfaceVariant),
        ),
      ),
    );
  }
}

class _SpectrumPainter extends CustomPainter {
  const _SpectrumPainter({
    required this.spectrum,
    required this.sending,
    required this.grid,
    required this.raw,
    required this.preGate,
    this.noiseFloorDb,
    this.opensAtDb,
    required this.floorLabel,
    required this.opensAtLabel,
  });

  /// The two dashed marks' labels.
  ///
  /// Passed in rather than looked up, because a painter has no
  /// `BuildContext`. They were literals — "floor" and "opens at" — so the
  /// only English left on a Russian analyser was drawn, not laid out, which
  /// is why no test and no reading of the widget tree would have found it.
  final String floorLabel;
  final String opensAtLabel;

  /// The tracked noise floor and the level a block must beat to be sent, in
  /// dBFS, or null while there is no trustworthy answer.
  ///
  /// **Both are measured after suppression**, which is the same signal the
  /// pre-gate trace is drawn from — so the marks and that trace can honestly be
  /// read against each other. The raw microphone trace is a different signal
  /// and the marks say nothing about it.
  final double? noiseFloorDb;
  final double? opensAtDb;

  final UiSpectrum spectrum;

  /// Whether that block actually left for somebody.
  ///
  /// Not `spectrum.transmitting` on its own. That is the chain's decision —
  /// "this would go out" — and it is deliberately independent of whether there
  /// is a server, because a diagnostic recording made alone still needs it. On
  /// this display, though, green claims the audio *went*, and with nothing
  /// connected it went nowhere. An iPhone in a room with people in it showed
  /// green bars while connected to no server at all; the Android emulator only
  /// looked right because its microphone hears silence.
  final bool sending;
  final Color grid;
  final Color raw;
  final Color preGate;

  /// The sent trace's colour, which is the one piece of state this display
  /// carries that the shapes cannot.
  ///
  /// A flat sent trace means the same shape whether the gate shut or nobody
  /// spoke, and those are opposite diagnoses — so live is a pale green and idle
  /// is grey, and the difference is visible at a glance without reading a
  /// label.
  /// Half transparent so the two thin traces stay readable *through* the bars
  /// rather than being buried by them. The bars are the body of the display and
  /// the lines are what it was made from; at full opacity the body wins and the
  /// comparison — which is the entire point — is lost.
  static Color sentColour(bool transmitting) => transmitting
      ? StatusColors.connected.withValues(alpha: 0.5)
      : const Color(0xFF8A93A0).withValues(alpha: 0.5);

  @override
  void paint(Canvas canvas, Size size) {
    if (spectrum.centresHz.isEmpty) return;
    final floor = spectrum.floorDb;

    double y(double db) {
      final t = ((db - floor) / (0 - floor)).clamp(0.0, 1.0);
      return size.height - t * size.height;
    }

    final lines = Paint()
      ..color = grid
      ..strokeWidth = 1;
    // Every 20 dB, so the eye has a scale without the grid competing with data.
    for (var db = floor; db <= 0; db += 20) {
      final yy = y(db);
      canvas.drawLine(Offset(0, yy), Offset(size.width, yy), lines);
    }

    // The two gate levels, under the traces so they read as a scale rather
    // than as data. Dashed, because a solid line at this weight is
    // indistinguishable from the 20 dB grid and would be read as one.
    void mark(double? db, Color colour, String label) {
      if (db == null || !db.isFinite || db < floor || db > 0) return;
      final yy = y(db);
      final dash = Paint()
        ..color = colour
        ..strokeWidth = 1;
      for (var x = 0.0; x < size.width; x += 7) {
        canvas.drawLine(Offset(x, yy), Offset(x + 4, yy), dash);
      }
      final text = TextPainter(
        text: TextSpan(
          text: label,
          style: TextStyle(fontSize: 9, color: colour),
        ),
        textDirection: TextDirection.ltr,
      )..layout();
      // Above its line where there is room, below it at the very top, so the
      // label never leaves the plot.
      final ty = yy - text.height - 1 < 0 ? yy + 1 : yy - text.height - 1;
      text.paint(canvas, Offset(2, ty));
    }

    // Drawn floor first: where the two coincide — a quiet room, where the
    // threshold sits just over the floor — the one that decides is the one
    // that should be legible.
    mark(noiseFloorDb, grid.withValues(alpha: 0.9), floorLabel);
    mark(opensAtDb, StatusColors.connecting.withValues(alpha: 0.7), opensAtLabel);

    final bands = spectrum.centresHz.length;
    final slot = size.width / bands;

    // Sent first as filled bars, so it reads as the body of the display and the
    // two thin lines read as what it was made from.
    final bars = Paint()..color = sentColour(sending);
    for (var i = 0; i < bands; i++) {
      final top = y(spectrum.sentDb[i]);
      if (top >= size.height) continue;
      canvas.drawRect(
        Rect.fromLTRB(i * slot + 0.5, top, (i + 1) * slot - 0.5, size.height),
        bars,
      );
    }

    void trace(List<double> db, Color colour) {
      final path = Path();
      for (var i = 0; i < bands; i++) {
        final x = i * slot + slot / 2;
        final yy = y(db[i]);
        if (i == 0) {
          path.moveTo(x, yy);
        } else {
          path.lineTo(x, yy);
        }
      }
      canvas.drawPath(
        path,
        Paint()
          ..color = colour
          ..style = PaintingStyle.stroke
          ..strokeWidth = 1.4
          ..strokeJoin = StrokeJoin.round,
      );
    }

    trace(spectrum.rawDb, raw);
    trace(spectrum.preGateDb, preGate);
  }

  @override
  bool shouldRepaint(_SpectrumPainter old) =>
      old.spectrum.seq != spectrum.seq ||
      old.sending != sending ||
      // The gate marks move on their own clock: the floor tracker settles
      // while the spectrum is unchanged, and a mark that only redrew when a
      // new frame arrived would sit at a stale level through exactly the
      // moments worth watching.
      old.noiseFloorDb != noiseFloorDb ||
      old.opensAtDb != opensAtDb ||
      // Switching language changes nothing else here — same frame, same
      // levels — so without this the plot keeps its old labels until the next
      // block arrives, which on a settled analyser can be a visible while.
      old.floorLabel != floorLabel ||
      old.opensAtLabel != opensAtLabel;
}

/// The processing chain as a row of dots, in the order audio passes through it.
class _ChainDots extends StatelessWidget {
  const _ChainDots({required this.status});

  final UiChainStatus status;

  @override
  Widget build(BuildContext context) {
    final l = L.of(context);
    return Wrap(
      spacing: 12,
      runSpacing: 8,
      children: [
        for (final stage in status.stages)
          _Dot(
            label: _label(l, stage),
            state: stage.state,
            value: stage.value,
            disabled: status.disabledStages.contains(stage.id),
            // Amber name, not just an amber dot.
            //
            // **Most amber on this row is transient and one kind is not.** The
            // echo canceller goes amber while it converges, the AGC while it
            // is at its ceiling, the gate while it is closed — all of them
            // describe this instant and will be green again shortly. The
            // enhancer's amber says it has *permanently given something up on
            // this device*, which is the same fact the strike-through carries
            // one step further on. Colouring the name is what separates the
            // two: a state you are watching, against a state you are stuck
            // with.
            degraded: stage.id == 'enhancer' && status.enhancerEffort > 0,
          ),
      ],
    );
  }

  /// Composed here rather than sent from Rust: everything else on this panel is
  /// translated, and a message built in the engine would be the one string a
  /// translator could not reach.
  String _label(L l, UiStage stage) => switch (stage.id) {
    // Listed in the order the chain runs them, matching the order the bridge
    // sends. A lookup does not care, but the next person reading it does.
    // The canceller is ahead of the enhancer — `engine.rs` says why.
    'aec' => l.diagStageEcho,
    'enhancer' => l.diagStageEnhancer,
    'rnnoise' => l.diagStageSuppressor,
    'vad' => l.diagStageVoice,
    'gate' => l.diagStageGate,
    'agc' => l.diagStageLevel,
    'feedback' => l.diagStageFeedback,
    'dehiss' => l.diagStageHiss,
    'background' => l.diagStageBackground,
    'transmit' => l.diagStageTransmit,
    _ => stage.id,
  };
}

class _Dot extends StatelessWidget {
  const _Dot({
    required this.label,
    required this.state,
    required this.value,
    this.disabled = false,
    this.degraded = false,
  });

  final String label;
  final StageState state;
  final double value;

  /// Still running, but the performance ladder has taken something off it.
  ///
  /// One step short of [disabled], and shown the same way for the same reason
  /// — an amber name means "this device gave this up", where an amber dot on
  /// its own only means "this stage is busy right now".
  final bool degraded;

  /// Switched off by the performance ladder, rather than idle.
  ///
  /// **The distinction the strike-through exists for.** A stage that is not
  /// running publishes the same greys and zeroes as one that is running with
  /// nothing to do, so without this a crippled chain and a quiet one look
  /// identical — which is precisely the class of blind spot that cost this
  /// project an evening over the input meter.
  final bool disabled;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    // The app's own status vocabulary, so a dot here means what a dot means
    // everywhere else in the interface.
    final colour = disabled
        ? StatusColors.connecting
        : switch (state) {
            StageState.good => StatusColors.connected,
            StageState.warn => StatusColors.connecting,
            StageState.bad => StatusColors.failed,
            StageState.off => scheme.onSurfaceVariant.withValues(alpha: 0.35),
          };

    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Container(
          width: 8,
          height: 8,
          decoration: BoxDecoration(
            // Hollow when it is not running: a filled dot says "this stage has
            // an opinion", and a stage that has been switched off does not.
            color: disabled ? null : colour,
            border: disabled ? Border.all(color: colour, width: 1.5) : null,
            shape: BoxShape.circle,
          ),
        ),
        const SizedBox(width: 5),
        Text(
          label,
          style: TextStyle(
            fontSize: 11,
            // **Dimmed when switched off, amber only when degraded.**
            //
            // Both used to be amber, and the strike-through was amber on top
            // of amber: at 11 px a same-coloured line through same-coloured
            // glyphs is not a strike-through, it is slightly bolder text.
            // Magnifying a screenshot five times showed the line was there and
            // being drawn correctly the whole time — it simply could not be
            // seen at the size it ships at, which is the only size that counts.
            //
            // So the two states are now told apart by more than a line nobody
            // can see: a stage still doing most of its job keeps the amber
            // name, and one that is not running at all goes quiet and gets a
            // line across it that contrasts with the letters it crosses.
            color: degraded
                ? StatusColors.connecting
                : scheme.onSurfaceVariant.withValues(alpha: disabled ? 0.6 : 1),
            // Struck through only when it is genuinely not running. A degraded
            // stage is still doing most of its job, and striking it out would
            // say otherwise.
            decoration: disabled ? TextDecoration.lineThrough : null,
            decorationColor: disabled ? StatusColors.connecting : null,
            decorationThickness: disabled ? 2 : null,
          ),
        ),
      ],
    );
  }
}
