// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'mumbleway.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `app`, `emit`, `send_command`, `status_of`, `to_profile`, `to_transmit`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `App`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Starts the engine. Must be called once before anything else.
Future<void> startEngine({required StartupOptions options}) =>
    RustLib.instance.api.crateApiMumblewayStartEngine(options: options);

/// Opens the event stream the UI listens on.
Stream<AppEvent> appEvents() =>
    RustLib.instance.api.crateApiMumblewayAppEvents();

/// Registers a server and starts its (initially idle) session.
Future<String> addServer({required ServerConfig config}) =>
    RustLib.instance.api.crateApiMumblewayAddServer(config: config);

/// Connects (or reconnects) a server.
Future<void> connectServer({required String serverId}) =>
    RustLib.instance.api.crateApiMumblewayConnectServer(serverId: serverId);

/// Disconnects a server. This is user-initiated, so it will not auto-reconnect.
Future<void> disconnectServer({required String serverId}) =>
    RustLib.instance.api.crateApiMumblewayDisconnectServer(serverId: serverId);

/// Accepts a changed server certificate and re-pins it.
Future<void> acceptCertificate({required String serverId}) =>
    RustLib.instance.api.crateApiMumblewayAcceptCertificate(serverId: serverId);

Future<void> joinChannel({required String serverId, required int channelId}) =>
    RustLib.instance.api.crateApiMumblewayJoinChannel(
      serverId: serverId,
      channelId: channelId,
    );

Future<void> sendText({required String serverId, required String message}) =>
    RustLib.instance.api.crateApiMumblewaySendText(
      serverId: serverId,
      message: message,
    );

Future<void> setSelfMute({required String serverId, required bool muted}) =>
    RustLib.instance.api.crateApiMumblewaySetSelfMute(
      serverId: serverId,
      muted: muted,
    );

/// Removes a server and stops its session.
Future<void> removeServer({required String serverId}) =>
    RustLib.instance.api.crateApiMumblewayRemoveServer(serverId: serverId);

/// Mutes or unmutes the local microphone.
void setMicrophoneMuted({required bool muted}) =>
    RustLib.instance.api.crateApiMumblewaySetMicrophoneMuted(muted: muted);

/// Silences all incoming audio.
void setDeafened({required bool deafened}) =>
    RustLib.instance.api.crateApiMumblewaySetDeafened(deafened: deafened);

/// Push-to-talk key state.
void setTransmitting({required bool on_}) =>
    RustLib.instance.api.crateApiMumblewaySetTransmitting(on_: on_);

/// Current microphone level in dBFS.
double inputLevelDb() => RustLib.instance.api.crateApiMumblewayInputLevelDb();

/// Available audio input device names.
Future<List<String>> audioInputDevices() =>
    RustLib.instance.api.crateApiMumblewayAudioInputDevices();

/// Available audio output device names.
Future<List<String>> audioOutputDevices() =>
    RustLib.instance.api.crateApiMumblewayAudioOutputDevices();

/// The SHA-256 fingerprint of our own client certificate, which servers use to
/// recognise a registered user.
Future<String> clientCertificateFingerprint() =>
    RustLib.instance.api.crateApiMumblewayClientCertificateFingerprint();

/// How many servers may be connected at once.
int maxConcurrentServers() =>
    RustLib.instance.api.crateApiMumblewayMaxConcurrentServers();

/// Default Mumble port, so the UI can prefill it.
int defaultPort() => RustLib.instance.api.crateApiMumblewayDefaultPort();

@freezed
sealed class AppEvent with _$AppEvent {
  const AppEvent._();

  const factory AppEvent.status(StatusUpdate field0) = AppEvent_Status;
  const factory AppEvent.users({
    required String serverId,
    required List<UiUser> users,
  }) = AppEvent_Users;
  const factory AppEvent.channels({
    required String serverId,
    required List<UiChannel> channels,
  }) = AppEvent_Channels;
  const factory AppEvent.text({
    required String serverId,
    required String from,
    required String message,
  }) = AppEvent_Text;
  const factory AppEvent.stats(UiStats field0) = AppEvent_Stats;

  /// Microphone level and speech detection, for the input meter.
  const factory AppEvent.inputLevel({
    required double levelDb,
    required bool speaking,
  }) = AppEvent_InputLevel;

  /// The server presented a certificate. `changed` means it differs from the
  /// pinned one and the user must decide.
  const factory AppEvent.certificate({
    required String serverId,
    required String fingerprint,
    required bool changed,
  }) = AppEvent_Certificate;
  const factory AppEvent.welcome({
    required String serverId,
    required String text,
  }) = AppEvent_Welcome;
}

/// Connection status, flattened for easy rendering.
enum ConnStatus {
  idle,
  connecting,
  handshaking,
  connected,
  reconnecting,
  disconnected,
  failed,
}

enum MicMode { voiceActivity, pushToTalk, continuous }

/// Noise-suppression strength, exposed as a simple selector.
enum NoiseSetting {
  off,
  light,
  standard,

  /// Aggressive profile for a motorcycle helmet.
  helmet,
}

/// A server the user has configured.
class ServerConfig {
  final String id;
  final String name;
  final String host;
  final int port;
  final String username;
  final String? password;
  final String? certFingerprint;

  const ServerConfig({
    required this.id,
    required this.name,
    required this.host,
    required this.port,
    required this.username,
    this.password,
    this.certFingerprint,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      password.hashCode ^
      certFingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerConfig &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          password == other.password &&
          certFingerprint == other.certFingerprint;
}

/// Startup options.
class StartupOptions {
  /// Writable directory for the client identity certificate.
  final String storageDir;
  final NoiseSetting noise;
  final MicMode micMode;

  const StartupOptions({
    required this.storageDir,
    required this.noise,
    required this.micMode,
  });

  @override
  int get hashCode => storageDir.hashCode ^ noise.hashCode ^ micMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartupOptions &&
          runtimeType == other.runtimeType &&
          storageDir == other.storageDir &&
          noise == other.noise &&
          micMode == other.micMode;
}

/// A status change for one server.
class StatusUpdate {
  final String serverId;
  final ConnStatus status;

  /// Human-readable detail: the failure reason, or empty when healthy.
  final String detail;

  /// Reconnect attempt number, 0 when not reconnecting.
  final int attempt;

  /// Milliseconds until the next retry, for a countdown.
  final BigInt retryInMs;

  const StatusUpdate({
    required this.serverId,
    required this.status,
    required this.detail,
    required this.attempt,
    required this.retryInMs,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      status.hashCode ^
      detail.hashCode ^
      attempt.hashCode ^
      retryInMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatusUpdate &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          status == other.status &&
          detail == other.detail &&
          attempt == other.attempt &&
          retryInMs == other.retryInMs;
}

class UiChannel {
  final int id;
  final String name;
  final int? parent;
  final String description;

  const UiChannel({
    required this.id,
    required this.name,
    this.parent,
    required this.description,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ parent.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiChannel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          parent == other.parent &&
          description == other.description;
}

class UiStats {
  final String serverId;
  final double tcpPingMs;
  final double udpPingMs;

  /// "udp" for the low-latency path, "tcp" when tunnelling.
  final String transport;

  const UiStats({
    required this.serverId,
    required this.tcpPingMs,
    required this.udpPingMs,
    required this.transport,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      tcpPingMs.hashCode ^
      udpPingMs.hashCode ^
      transport.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiStats &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          tcpPingMs == other.tcpPingMs &&
          udpPingMs == other.udpPingMs &&
          transport == other.transport;
}

class UiUser {
  final int session;
  final String name;
  final int channelId;
  final bool talking;
  final bool muted;
  final bool deafened;

  const UiUser({
    required this.session,
    required this.name,
    required this.channelId,
    required this.talking,
    required this.muted,
    required this.deafened,
  });

  @override
  int get hashCode =>
      session.hashCode ^
      name.hashCode ^
      channelId.hashCode ^
      talking.hashCode ^
      muted.hashCode ^
      deafened.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiUser &&
          runtimeType == other.runtimeType &&
          session == other.session &&
          name == other.name &&
          channelId == other.channelId &&
          talking == other.talking &&
          muted == other.muted &&
          deafened == other.deafened;
}
