// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'mumbleway.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `allocate_slot`, `app`, `config_to_profile`, `cue_for_moderation`, `cue_for_transition`, `emit`, `is_waiting`, `process_usage`, `send_command`, `status_of`, `to_profile`, `to_transmit`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `App`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Starts the engine. Must be called once before anything else.
Future<void> startEngine({required StartupOptions options}) =>
    RustLib.instance.api.crateApiMumblewayStartEngine(options: options);

/// Opens the event stream the UI listens on.
Stream<AppEvent> appEvents() =>
    RustLib.instance.api.crateApiMumblewayAppEvents();

/// Registers a server and starts its (initially idle) session.
Future<String> addServer({required ServerConfig config}) =>
    RustLib.instance.api.crateApiMumblewayAddServer(config: config);

/// Connects (or reconnects) a server.
Future<void> connectServer({required String serverId}) =>
    RustLib.instance.api.crateApiMumblewayConnectServer(serverId: serverId);

/// Disconnects a server. This is user-initiated, so it will not auto-reconnect.
Future<void> disconnectServer({required String serverId}) =>
    RustLib.instance.api.crateApiMumblewayDisconnectServer(serverId: serverId);

/// Accepts a changed server certificate and re-pins it.
Future<void> acceptCertificate({required String serverId}) =>
    RustLib.instance.api.crateApiMumblewayAcceptCertificate(serverId: serverId);

Future<void> joinChannel({required String serverId, required int channelId}) =>
    RustLib.instance.api.crateApiMumblewayJoinChannel(
      serverId: serverId,
      channelId: channelId,
    );

Future<void> sendText({required String serverId, required String message}) =>
    RustLib.instance.api.crateApiMumblewaySendText(
      serverId: serverId,
      message: message,
    );

Future<void> setSelfMute({required String serverId, required bool muted}) =>
    RustLib.instance.api.crateApiMumblewaySetSelfMute(
      serverId: serverId,
      muted: muted,
    );

/// Removes a server and stops its session.
Future<void> removeServer({required String serverId}) =>
    RustLib.instance.api.crateApiMumblewayRemoveServer(serverId: serverId);

/// Mutes or unmutes the local microphone.
void setMicrophoneMuted({required bool muted}) =>
    RustLib.instance.api.crateApiMumblewaySetMicrophoneMuted(muted: muted);

/// Silences all incoming audio.
void setDeafened({required bool deafened}) =>
    RustLib.instance.api.crateApiMumblewaySetDeafened(deafened: deafened);

/// Push-to-talk key state.
void setTransmitting({required bool on_}) =>
    RustLib.instance.api.crateApiMumblewaySetTransmitting(on_: on_);

/// Current microphone level in dBFS.
double inputLevelDb() => RustLib.instance.api.crateApiMumblewayInputLevelDb();

/// Available audio input device names.
Future<List<String>> audioInputDevices() =>
    RustLib.instance.api.crateApiMumblewayAudioInputDevices();

/// Available audio output device names.
Future<List<String>> audioOutputDevices() =>
    RustLib.instance.api.crateApiMumblewayAudioOutputDevices();

/// The SHA-256 fingerprint of our own client certificate, which servers use to
/// recognise a registered user.
Future<String> clientCertificateFingerprint() =>
    RustLib.instance.api.crateApiMumblewayClientCertificateFingerprint();

/// How many servers may be connected at once.
int maxConcurrentServers() =>
    RustLib.instance.api.crateApiMumblewayMaxConcurrentServers();

/// Default Mumble port, so the UI can prefill it.
int defaultPort() => RustLib.instance.api.crateApiMumblewayDefaultPort();

/// Queries a server's ping and occupancy without connecting or authenticating.
///
/// Never fails: an unreachable or non-responding server comes back with
/// `reachable == false`, because the caller is refreshing a list and a thrown
/// error per offline server would be noise.
Future<UiServerStatus> pingServer({
  required String serverId,
  required String host,
  required int port,
}) => RustLib.instance.api.crateApiMumblewayPingServer(
  serverId: serverId,
  host: host,
  port: port,
);

/// Opens or closes the microphone and speaker.
///
/// The engine holds no devices until this is called. Ask for them as a call is
/// being set up, not as the first word is spoken: opening a Bluetooth headset
/// means negotiating an SCO link, which takes one to two seconds and is
/// audible, and a rider who presses talk into a device that is still opening
/// loses the beginning of what they said. A connect already takes that long,
/// so asking here costs nothing that is not already being waited for.
///
/// Turning them on blocks until the device answers, because the answer is the
/// point: no microphone, a refused permission or a headset held by another app
/// are all things the rider can do something about, and all of them surface
/// here. Turning them off returns at once — there is nothing to wait for and
/// nothing that can fail.
Future<void> setAudioActive({required bool on_}) =>
    RustLib.instance.api.crateApiMumblewaySetAudioActive(on_: on_);

/// Selects capture and playback devices. `None` means the system default.
/// Takes effect within a few hundred milliseconds, without dropping sessions.
Future<void> setAudioDevices({String? input, String? output}) => RustLib
    .instance
    .api
    .crateApiMumblewaySetAudioDevices(input: input, output: output);

/// Currently selected devices as `(input, output)`.
Future<(String?, String?)> currentAudioDevices() =>
    RustLib.instance.api.crateApiMumblewayCurrentAudioDevices();

void setInputGainDb({required double db}) =>
    RustLib.instance.api.crateApiMumblewaySetInputGainDb(db: db);

double inputGainDb() => RustLib.instance.api.crateApiMumblewayInputGainDb();

void setOutputVolumeDb({required double db}) =>
    RustLib.instance.api.crateApiMumblewaySetOutputVolumeDb(db: db);

double outputVolumeDb() =>
    RustLib.instance.api.crateApiMumblewayOutputVolumeDb();

/// Playback level in dBFS, for an output meter.
double outputLevelDb() => RustLib.instance.api.crateApiMumblewayOutputLevelDb();

/// Loopback monitoring: hear your own processed voice, to check the microphone
/// and the noise-suppression setting.
void setMonitoring({required bool on_}) =>
    RustLib.instance.api.crateApiMumblewaySetMonitoring(on_: on_);

bool isMonitoring() => RustLib.instance.api.crateApiMumblewayIsMonitoring();

UiDiagnostics audioDiagnostics() =>
    RustLib.instance.api.crateApiMumblewayAudioDiagnostics();

void resetAudioGlitches() =>
    RustLib.instance.api.crateApiMumblewayResetAudioGlitches();

/// The latest analyser frame, and an ask for the next one.
///
/// **Calling this is what makes the engine do the work.** The analyser is the
/// most expensive thing in the capture chain and worth nothing when nobody is
/// looking, so it runs only while it is being asked for, and the ask expires
/// after half a second. There is deliberately no matching "stop": every
/// explicit stop has a path that misses it — the diagnostics panel is never
/// disposed, the app can be backgrounded, the engine can be restarted — and a
/// missed stop leaves three transforms per block running in a rider's pocket.
///
/// So: poll it while the panel is open, stop when it closes, and the cost stops
/// with it. `None` means no frame has been produced yet.
UiSpectrum? audioSpectrum() =>
    RustLib.instance.api.crateApiMumblewayAudioSpectrum();

/// Where each stage of the capture chain stands.
///
/// Free, and always current: the chain publishes this as it runs whether or not
/// anybody is reading. Unlike [`audio_spectrum`] it arms nothing.
UiChainStatus audioChainStatus() =>
    RustLib.instance.api.crateApiMumblewayAudioChainStatus();

/// Starts recording the microphone and what the chain decided about it.
///
/// **This writes the rider's microphone to storage.** It exists because every
/// measurement in this project was invalidated at once by discovering the
/// recordings behind it came from the phone's own microphone rather than the
/// headset's, and no amount of care in the analysis could have caught that.
/// Recording inside the app makes the audio the chain's own input by
/// construction.
///
/// Off unless asked for, started only from the diagnostics panel, and the
/// directory comes from the caller because only the Dart side knows where a
/// given platform lets an app put files a person can later get at.
void startDiagnosticRecording({
  required String directory,
  required String tag,
}) => RustLib.instance.api.crateApiMumblewayStartDiagnosticRecording(
  directory: directory,
  tag: tag,
);

/// Stops the recording and closes the files, returning the blocks that were
/// dropped because storage could not keep up.
///
/// Waits for the writer to flush. That is a few milliseconds and it is not
/// optional: the next thing that happens is a rider sharing the file, and a
/// file still held open shares as a truncated one.
BigInt stopDiagnosticRecording() =>
    RustLib.instance.api.crateApiMumblewayStopDiagnosticRecording();

/// Where the recording stands. Free to call, and safe before the engine is up.
UiRecordingState diagnosticRecordingState() =>
    RustLib.instance.api.crateApiMumblewayDiagnosticRecordingState();

/// Everything the engine has logged so far.
///
/// The stream only carries lines recorded after the UI attached to it, and the
/// interesting ones — why the audio device would not open, what the first
/// connect said — are written before that. This fetches those. Deliberately not
/// gated on the engine being up: when startup is what failed, this is the only
/// place the reason exists.
List<UiLogEntry> recentLogs() =>
    RustLib.instance.api.crateApiMumblewayRecentLogs();

/// Empties the log, so a reproduction attempt starts from a clean sheet.
void clearLogs() => RustLib.instance.api.crateApiMumblewayClearLogs();

/// Sounds an arrival or a departure from the channel.
///
/// Driven from the roster rather than the audio path, because someone joining
/// makes no sound of their own — which is exactly why it needs a cue.
void playParticipantCue({required bool joined}) =>
    RustLib.instance.api.crateApiMumblewayPlayParticipantCue(joined: joined);

/// A short room tail under incoming voices, so a gated talker does not stop
/// like a switch being thrown.
void setReverb({required bool on_}) =>
    RustLib.instance.api.crateApiMumblewaySetReverb(on_: on_);

bool isReverbEnabled() =>
    RustLib.instance.api.crateApiMumblewayIsReverbEnabled();

/// Levels incoming speakers towards a common loudness.
void setLevelNormalisation({required bool on_}) =>
    RustLib.instance.api.crateApiMumblewaySetLevelNormalisation(on_: on_);

bool isLevelNormalisationEnabled() =>
    RustLib.instance.api.crateApiMumblewayIsLevelNormalisationEnabled();

/// How much incoming audio to hold back before playing it, in milliseconds.
///
/// The trade the rider is making is delay against dropouts, and which way it
/// should go is a property of the network they are on rather than of the app.
/// Rounded to whole 20 ms packets, which is the unit voice arrives in.
void setJitterBufferMs({required int ms}) =>
    RustLib.instance.api.crateApiMumblewaySetJitterBufferMs(ms: ms);

int jitterBufferMs() => RustLib.instance.api.crateApiMumblewayJitterBufferMs();

/// The range the setting above accepts, as `(minimum, maximum, step)` in ms.
///
/// Reported rather than written into the interface twice: the bounds come from
/// the buffer's own frame arithmetic, and a slider that let somebody pick a
/// value the engine then silently rounded would be lying about what it set.
(int, int, int) jitterBufferBoundsMs() =>
    RustLib.instance.api.crateApiMumblewayJitterBufferBoundsMs();

/// Acoustic echo cancellation, applied to the microphone before anything else.
void setEchoCancellation({required bool on_}) =>
    RustLib.instance.api.crateApiMumblewaySetEchoCancellation(on_: on_);

bool isEchoCancellationEnabled() =>
    RustLib.instance.api.crateApiMumblewayIsEchoCancellationEnabled();

/// How the microphone opens. Takes effect on the next block, not the next
/// launch — which is what it used to do, silently.
void setMicMode({required MicMode mode}) =>
    RustLib.instance.api.crateApiMumblewaySetMicMode(mode: mode);

/// How hard the noise suppressor works. Also live rather than at launch.
void setNoise({required NoiseSetting noise}) =>
    RustLib.instance.api.crateApiMumblewaySetNoise(noise: noise);

/// Applied after the echo canceller, to whatever it could not model.
void setFeedbackGuard({required FeedbackGuardMode mode}) =>
    RustLib.instance.api.crateApiMumblewaySetFeedbackGuard(mode: mode);

void setDehiss({required DehissOption mode}) =>
    RustLib.instance.api.crateApiMumblewaySetDehiss(mode: mode);

/// Plays a tone on the output device, to check the speaker choice.
void playTestTone({required int millis}) =>
    RustLib.instance.api.crateApiMumblewayPlayTestTone(millis: millis);

void stopTestTone() => RustLib.instance.api.crateApiMumblewayStopTestTone();

/// Gain limits, so the UI can build sliders that match the engine.
Float32List gainLimits() => RustLib.instance.api.crateApiMumblewayGainLimits();

/// Silences another user for us only. Always permitted.
Future<void> setUserLocalMute({
  required String serverId,
  required int session,
  required bool muted,
}) => RustLib.instance.api.crateApiMumblewaySetUserLocalMute(
  serverId: serverId,
  session: session,
  muted: muted,
);

/// Silences another user for everyone. Requires the Mute permission; without it
/// the server replies with a permission-denied message that surfaces as text.
Future<void> setUserServerMute({
  required String serverId,
  required int session,
  required bool muted,
}) => RustLib.instance.api.crateApiMumblewaySetUserServerMute(
  serverId: serverId,
  session: session,
  muted: muted,
);

/// Deafens another user server-side. Also permission-gated.
Future<void> setUserServerDeaf({
  required String serverId,
  required int session,
  required bool deaf,
}) => RustLib.instance.api.crateApiMumblewaySetUserServerDeaf(
  serverId: serverId,
  session: session,
  deaf: deaf,
);

/// Channel to join automatically on every future connect. `None` clears it.
Future<void> setDefaultChannel({required String serverId, String? channel}) =>
    RustLib.instance.api.crateApiMumblewaySetDefaultChannel(
      serverId: serverId,
      channel: channel,
    );

/// Removes a user from the server. Requires the Kick permission; without it the
/// server answers with a permission-denied message that arrives as text.
///
/// This is a kick, not a ban — they may reconnect immediately.
Future<void> kickUser({
  required String serverId,
  required int session,
  required String reason,
}) => RustLib.instance.api.crateApiMumblewayKickUser(
  serverId: serverId,
  session: session,
  reason: reason,
);

/// Builds a `mumble://` invite link for a server and channel.
///
/// `include_password` is a deliberate choice by the caller: a link carrying a
/// password grants access to anyone who ever sees it, including whatever chat
/// app it travels through.
Future<String> buildInviteLink({
  required ServerConfig config,
  String? channel,
  required bool includePassword,
}) => RustLib.instance.api.crateApiMumblewayBuildInviteLink(
  config: config,
  channel: channel,
  includePassword: includePassword,
);

/// Builds a shareable JSON profile file for one server.
Future<String> buildInviteFile({
  required ServerConfig config,
  String? channel,
  required bool includePassword,
}) => RustLib.instance.api.crateApiMumblewayBuildInviteFile(
  config: config,
  channel: channel,
  includePassword: includePassword,
);

/// Builds a JSON file containing every supplied server, for backup or transfer.
Future<String> exportServers({required List<ServerConfig> configs}) =>
    RustLib.instance.api.crateApiMumblewayExportServers(configs: configs);

/// Parses a `mumble://` link or a JSON profile file into server definitions.
///
/// Nothing is connected or saved here; the caller decides what to keep.
Future<List<ServerConfig>> importServers({
  required String text,
  required String fallbackUsername,
}) => RustLib.instance.api.crateApiMumblewayImportServers(
  text: text,
  fallbackUsername: fallbackUsername,
);

/// Feeds the output a stretch of a recording being previewed.
///
/// The transport is on the Dart side deliberately. Previewing means reading a
/// file, and a file read has no business anywhere near the audio thread — so
/// what crosses this boundary is decoded samples, and this end is a queue.
///
/// Returns how many were accepted, which is fewer than offered once the queue
/// is full. The caller uses that to pace itself rather than to discover later
/// that its playhead has drifted from what anybody heard.
int previewPush({required List<double> samples}) =>
    RustLib.instance.api.crateApiMumblewayPreviewPush(samples: samples);

/// Samples still waiting to be heard.
///
/// The playhead is what was pushed minus this. It is the only honest source
/// for it: the queue drains at the speaker's rate, and a timer counting
/// forwards from "play" would run ahead the moment the device buffered.
int previewQueued() => RustLib.instance.api.crateApiMumblewayPreviewQueued();

/// Stops a preview, and is also how a seek starts.
void previewClear() => RustLib.instance.api.crateApiMumblewayPreviewClear();

@freezed
sealed class AppEvent with _$AppEvent {
  const AppEvent._();

  const factory AppEvent.status(StatusUpdate field0) = AppEvent_Status;
  const factory AppEvent.users({
    required String serverId,
    required List<UiUser> users,
  }) = AppEvent_Users;
  const factory AppEvent.channels({
    required String serverId,
    required List<UiChannel> channels,
  }) = AppEvent_Channels;
  const factory AppEvent.text({
    required String serverId,
    required String from,
    required String message,
  }) = AppEvent_Text;
  const factory AppEvent.stats(UiStats field0) = AppEvent_Stats;

  /// Microphone level and speech detection, for the input meter.
  const factory AppEvent.inputLevel({
    required double levelDb,
    required bool speaking,

    /// Level voice activation opens at, tracking the background noise.
    required double thresholdDb,

    /// The tracked background noise itself. The gap up to `threshold_db`
    /// is the margin, which is what makes a rising floor readable as
    /// wind rather than as a mis-set control.
    required double noiseFloorDb,
  }) = AppEvent_InputLevel;

  /// Level of each speaker currently producing audio.
  ///
  /// The server never reports who is talking, so the only honest source is
  /// the audio itself.
  const factory AppEvent.speakerLevels({required List<UiSpeakerLevel> levels}) =
      AppEvent_SpeakerLevels;

  /// Someone else changed our mute or deafen state.
  const factory AppEvent.moderated({
    required String serverId,
    bool? muted,
    bool? deafened,
    required String by,
  }) = AppEvent_Moderated;

  /// The server presented a certificate. `changed` means it differs from the
  /// pinned one and the user must decide.
  const factory AppEvent.certificate({
    required String serverId,
    required String fingerprint,
    required bool changed,
  }) = AppEvent_Certificate;
  const factory AppEvent.welcome({
    required String serverId,
    required String text,
  }) = AppEvent_Welcome;

  /// Our own session id on this server. Needed to work out which channel we
  /// are in, and to keep ourselves out of the "other users" roster.
  const factory AppEvent.selfSession({
    required String serverId,
    required int session,
  }) = AppEvent_SelfSession;

  /// Lines the engine wrote about itself, for the log in the diagnostics
  /// panel and for the platform log behind it.
  const factory AppEvent.log({required List<UiLogEntry> entries}) =
      AppEvent_Log;
}

/// Connection status, flattened for easy rendering.
enum ConnStatus {
  idle,
  connecting,
  handshaking,
  connected,
  reconnecting,
  disconnected,
  failed,
}

/// How to deal with the steady hiss a microphone adds under speech.
///
/// Separate from noise suppression, which handles the road and the wind. Those
/// are loud and change with speed; hiss is quiet, high and unvarying, and the
/// two want opposite treatments.
enum DehissOption {
  /// Change nothing. The default, because both of the others discard
  /// something and a voice link that is working should be left alone.
  off,

  /// Turns quiet passages down further, in proportion to how quiet they are.
  /// Cannot make speech sound synthetic; can make the floor breathe.
  expander,

  /// Learns the noise spectrum while nobody talks and subtracts it per
  /// frequency. Removes hiss from under speech as well as between words; the
  /// price is a faint flicker in the gaps if it is pushed hard.
  spectral,
}

/// What to do about the speaker being heard by the microphone.
///
/// Distinct approaches rather than strengths of one: see `audio::feedback`.
enum FeedbackGuardMode { off, duck, howlGuard, residual }

enum MicMode { voiceActivity, pushToTalk, continuous }

/// Noise-suppression strength, exposed as a simple selector.
enum NoiseSetting {
  off,
  light,
  standard,

  /// Aggressive profile for a motorcycle helmet.
  helmet,

  /// Picks between the four above from what the microphone is hearing.
  ///
  /// Last in the list rather than first: it is an extra option, and putting
  /// it at the top would renumber every setting a rider has already stored.
  auto,
}

/// A server the user has configured.
class ServerConfig {
  final String id;
  final String name;
  final String host;
  final int port;
  final String username;
  final String? password;
  final String? certFingerprint;

  /// Channel to drop into on connecting, as the link carried it.
  ///
  /// Here because an invitation is about a place as much as a server: the
  /// `mumble://` scheme puts the channel in the path, the core has always
  /// parsed it, and it was then dropped on the way across this boundary —
  /// so following a link that named a channel landed the guest in the root
  /// and left them to find the conversation themselves.
  final String? defaultChannel;

  const ServerConfig({
    required this.id,
    required this.name,
    required this.host,
    required this.port,
    required this.username,
    this.password,
    this.certFingerprint,
    this.defaultChannel,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      password.hashCode ^
      certFingerprint.hashCode ^
      defaultChannel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerConfig &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          password == other.password &&
          certFingerprint == other.certFingerprint &&
          defaultChannel == other.defaultChannel;
}

/// How a stage of the chain is doing.
enum StageState {
  /// Switched off, so it has no opinion.
  off,

  /// Working, and passing audio on.
  good,

  /// Working, but holding something back.
  warn,

  /// Stopping audio here.
  bad,
}

/// Startup options.
class StartupOptions {
  /// Writable directory for the client identity certificate.
  final String storageDir;
  final NoiseSetting noise;
  final MicMode micMode;

  const StartupOptions({
    required this.storageDir,
    required this.noise,
    required this.micMode,
  });

  @override
  int get hashCode => storageDir.hashCode ^ noise.hashCode ^ micMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartupOptions &&
          runtimeType == other.runtimeType &&
          storageDir == other.storageDir &&
          noise == other.noise &&
          micMode == other.micMode;
}

/// A status change for one server.
class StatusUpdate {
  final String serverId;
  final ConnStatus status;

  /// Human-readable detail: the failure reason, or empty when healthy.
  final String detail;

  /// Reconnect attempt number, 0 when not reconnecting.
  final int attempt;

  /// Milliseconds until the next retry, for a countdown.
  final BigInt retryInMs;

  const StatusUpdate({
    required this.serverId,
    required this.status,
    required this.detail,
    required this.attempt,
    required this.retryInMs,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      status.hashCode ^
      detail.hashCode ^
      attempt.hashCode ^
      retryInMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatusUpdate &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          status == other.status &&
          detail == other.detail &&
          attempt == other.attempt &&
          retryInMs == other.retryInMs;
}

/// The capture chain, stage by stage, as of the last block.
class UiChainStatus {
  /// In order, from the microphone to the wire.
  final List<UiStage> stages;

  /// Whether voice activation would open right now, whatever mode is set.
  final bool wouldPassVoiceActivated;

  /// Whether audio actually went out on the last block.
  final bool transmitting;

  /// Still starting up; nothing above should be believed yet.
  final bool warmingUp;

  /// Level, the floor under it, and the level needed to open. All dBFS.
  final double levelDb;
  final double noiseFloorDb;
  final double activationThresholdDb;

  const UiChainStatus({
    required this.stages,
    required this.wouldPassVoiceActivated,
    required this.transmitting,
    required this.warmingUp,
    required this.levelDb,
    required this.noiseFloorDb,
    required this.activationThresholdDb,
  });

  @override
  int get hashCode =>
      stages.hashCode ^
      wouldPassVoiceActivated.hashCode ^
      transmitting.hashCode ^
      warmingUp.hashCode ^
      levelDb.hashCode ^
      noiseFloorDb.hashCode ^
      activationThresholdDb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiChainStatus &&
          runtimeType == other.runtimeType &&
          stages == other.stages &&
          wouldPassVoiceActivated == other.wouldPassVoiceActivated &&
          transmitting == other.transmitting &&
          warmingUp == other.warmingUp &&
          levelDb == other.levelDb &&
          noiseFloorDb == other.noiseFloorDb &&
          activationThresholdDb == other.activationThresholdDb;
}

class UiChannel {
  final int id;
  final String name;
  final int? parent;
  final String description;

  /// Users currently in this channel.
  final int userCount;
  final int maxUsers;

  const UiChannel({
    required this.id,
    required this.name,
    this.parent,
    required this.description,
    required this.userCount,
    required this.maxUsers,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      parent.hashCode ^
      description.hashCode ^
      userCount.hashCode ^
      maxUsers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiChannel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          parent == other.parent &&
          description == other.description &&
          userCount == other.userCount &&
          maxUsers == other.maxUsers;
}

/// Everything the diagnostics panel shows, gathered in one call.
///
/// One struct rather than a handful of getters because these numbers are only
/// meaningful against each other: playback gaps mean something different when
/// the microphone is also dropping, and invented audio means something
/// different when losses are climbing.
class UiDiagnostics {
  /// Audio the output had to invent because nothing was ready to play.
  final BigInt playbackGapMs;

  /// Microphone audio discarded because the processing fell behind.
  final BigInt captureDroppedMs;

  /// Incoming audio decoded from real packets.
  final BigInt incomingRealMs;

  /// Incoming audio synthesised to cover gaps.
  final BigInt incomingInventedMs;

  /// Gaps in incoming streams that had to be concealed.
  final BigInt lostPackets;

  /// Deepest jitter buffer currently held, in milliseconds.
  final BigInt jitterBufferMs;

  /// Speakers the mixer is currently tracking.
  final int speakers;
  final BigInt bytesIn;
  final BigInt bytesOut;
  final BigInt voicePacketsIn;
  final BigInt voicePacketsOut;

  /// Share of one core this process is using, as a percentage.
  final double cpuPercent;

  /// Resident memory, in mebibytes.
  final double memoryMb;

  const UiDiagnostics({
    required this.playbackGapMs,
    required this.captureDroppedMs,
    required this.incomingRealMs,
    required this.incomingInventedMs,
    required this.lostPackets,
    required this.jitterBufferMs,
    required this.speakers,
    required this.bytesIn,
    required this.bytesOut,
    required this.voicePacketsIn,
    required this.voicePacketsOut,
    required this.cpuPercent,
    required this.memoryMb,
  });

  @override
  int get hashCode =>
      playbackGapMs.hashCode ^
      captureDroppedMs.hashCode ^
      incomingRealMs.hashCode ^
      incomingInventedMs.hashCode ^
      lostPackets.hashCode ^
      jitterBufferMs.hashCode ^
      speakers.hashCode ^
      bytesIn.hashCode ^
      bytesOut.hashCode ^
      voicePacketsIn.hashCode ^
      voicePacketsOut.hashCode ^
      cpuPercent.hashCode ^
      memoryMb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiDiagnostics &&
          runtimeType == other.runtimeType &&
          playbackGapMs == other.playbackGapMs &&
          captureDroppedMs == other.captureDroppedMs &&
          incomingRealMs == other.incomingRealMs &&
          incomingInventedMs == other.incomingInventedMs &&
          lostPackets == other.lostPackets &&
          jitterBufferMs == other.jitterBufferMs &&
          speakers == other.speakers &&
          bytesIn == other.bytesIn &&
          bytesOut == other.bytesOut &&
          voicePacketsIn == other.voicePacketsIn &&
          voicePacketsOut == other.voicePacketsOut &&
          cpuPercent == other.cpuPercent &&
          memoryMb == other.memoryMb;
}

/// One line of the engine's log.
class UiLogEntry {
  /// Monotonic within a run, so the reader can ask for what it has not seen
  /// without relying on timestamps being unique.
  final BigInt seq;
  final BigInt atMs;

  /// 0 trace, 1 debug, 2 info, 3 warn, 4 error. A number rather than an enum
  /// because the UI orders and filters by severity, and an enum would have to
  /// be mapped back to exactly this order to do it.
  final int level;

  /// The subsystem that spoke: `session`, `engine`, `manager`.
  final String target;
  final String message;

  const UiLogEntry({
    required this.seq,
    required this.atMs,
    required this.level,
    required this.target,
    required this.message,
  });

  @override
  int get hashCode =>
      seq.hashCode ^
      atMs.hashCode ^
      level.hashCode ^
      target.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiLogEntry &&
          runtimeType == other.runtimeType &&
          seq == other.seq &&
          atMs == other.atMs &&
          level == other.level &&
          target == other.target &&
          message == other.message;
}

/// Whether a diagnostic recording is running, and how it is doing.
class UiRecordingState {
  final bool active;

  /// Blocks storage could not keep up with. Shown rather than hidden: a
  /// recording with gaps is still useful, and a recording with gaps nobody
  /// knows about is a measurement waiting to be wrong.
  final BigInt droppedBlocks;

  /// Where the files are, so the panel can offer to share them.
  final String directory;

  const UiRecordingState({
    required this.active,
    required this.droppedBlocks,
    required this.directory,
  });

  @override
  int get hashCode =>
      active.hashCode ^ droppedBlocks.hashCode ^ directory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiRecordingState &&
          runtimeType == other.runtimeType &&
          active == other.active &&
          droppedBlocks == other.droppedBlocks &&
          directory == other.directory;
}

/// What an unauthenticated status probe reported about a server.
class UiServerStatus {
  final String serverId;
  final bool reachable;
  final double pingMs;
  final int users;
  final int maxUsers;
  final String version;

  const UiServerStatus({
    required this.serverId,
    required this.reachable,
    required this.pingMs,
    required this.users,
    required this.maxUsers,
    required this.version,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      reachable.hashCode ^
      pingMs.hashCode ^
      users.hashCode ^
      maxUsers.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiServerStatus &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          reachable == other.reachable &&
          pingMs == other.pingMs &&
          users == other.users &&
          maxUsers == other.maxUsers &&
          version == other.version;
}

/// One speaker's current loudness.
class UiSpeakerLevel {
  final String serverId;
  final int session;

  /// dBFS, falling towards silence when they stop.
  final double levelDb;

  const UiSpeakerLevel({
    required this.serverId,
    required this.session,
    required this.levelDb,
  });

  @override
  int get hashCode => serverId.hashCode ^ session.hashCode ^ levelDb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiSpeakerLevel &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          session == other.session &&
          levelDb == other.levelDb;
}

/// One frame of the capture-chain analyser.
///
/// Band levels are dBFS, floored, one entry per band, and the three traces are
/// always the same length as `centres_hz`.
class UiSpectrum {
  /// Centre frequency of each band. Sent every frame rather than fetched
  /// once, so the axis and the data can never disagree about how many bands
  /// there are.
  final Float32List centresHz;

  /// The microphone, before any processing.
  final Float32List rawDb;

  /// What the noise gate was about to judge.
  final Float32List preGateDb;

  /// What reached the encoder. Drawn whether or not it was transmitted;
  /// `transmitting` is what says which.
  final Float32List sentDb;

  /// Quietest level in the data, for scaling the axis.
  final double floorDb;

  /// How tonal the pre-gate signal is, 0..1.
  final double harmonicity;

  /// Whether the block this frame describes actually went out.
  final bool transmitting;

  /// Frame counter. If this stops moving the worker has stopped, which on
  /// screen is indistinguishable from silence unless the reader checks.
  final BigInt seq;

  const UiSpectrum({
    required this.centresHz,
    required this.rawDb,
    required this.preGateDb,
    required this.sentDb,
    required this.floorDb,
    required this.harmonicity,
    required this.transmitting,
    required this.seq,
  });

  @override
  int get hashCode =>
      centresHz.hashCode ^
      rawDb.hashCode ^
      preGateDb.hashCode ^
      sentDb.hashCode ^
      floorDb.hashCode ^
      harmonicity.hashCode ^
      transmitting.hashCode ^
      seq.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiSpectrum &&
          runtimeType == other.runtimeType &&
          centresHz == other.centresHz &&
          rawDb == other.rawDb &&
          preGateDb == other.preGateDb &&
          sentDb == other.sentDb &&
          floorDb == other.floorDb &&
          harmonicity == other.harmonicity &&
          transmitting == other.transmitting &&
          seq == other.seq;
}

/// One stage of the capture chain.
///
/// Carries no prose. The panel is fully localised, and a message composed in
/// Rust would be the one string in it that no translator can reach — so Dart
/// builds the label from `id`, `state` and `value`.
class UiStage {
  /// Stable identifier: `aec`, `rnnoise`, `gate`, `vad`, `harmonicity`,
  /// `agc`, `dehiss`, `feedback`, `profile`, `transmit`.
  final String id;
  final StageState state;

  /// The one number that stage is about, in whatever unit suits it — dB for
  /// the AEC and the AGC, 0..1 for harmonicity, unused elsewhere.
  final double value;

  const UiStage({required this.id, required this.state, required this.value});

  @override
  int get hashCode => id.hashCode ^ state.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiStage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          state == other.state &&
          value == other.value;
}

class UiStats {
  final String serverId;
  final double tcpPingMs;
  final double udpPingMs;

  /// "udp" for the low-latency path, "tcp" when tunnelling.
  final String transport;

  const UiStats({
    required this.serverId,
    required this.tcpPingMs,
    required this.udpPingMs,
    required this.transport,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      tcpPingMs.hashCode ^
      udpPingMs.hashCode ^
      transport.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiStats &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          tcpPingMs == other.tcpPingMs &&
          udpPingMs == other.udpPingMs &&
          transport == other.transport;
}

class UiUser {
  final int session;
  final String name;
  final int channelId;
  final bool talking;

  /// Muted server-side or by themselves — nobody hears them.
  final bool muted;
  final bool deafened;

  /// Silenced by us alone. Needs no permission and is invisible to others.
  final bool localMute;

  /// One word for the roster: talking, silent, muted, deafened, muted for you.
  final String status;

  const UiUser({
    required this.session,
    required this.name,
    required this.channelId,
    required this.talking,
    required this.muted,
    required this.deafened,
    required this.localMute,
    required this.status,
  });

  @override
  int get hashCode =>
      session.hashCode ^
      name.hashCode ^
      channelId.hashCode ^
      talking.hashCode ^
      muted.hashCode ^
      deafened.hashCode ^
      localMute.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiUser &&
          runtimeType == other.runtimeType &&
          session == other.session &&
          name == other.name &&
          channelId == other.channelId &&
          talking == other.talking &&
          muted == other.muted &&
          deafened == other.deafened &&
          localMute == other.localMute &&
          status == other.status;
}
